// ========== AGENT GRIMOIRE DATA ==========
// Bundle + Tier system for Agent Grimoire marketplace
// Last updated: 2026-02-24

window.BUNDLES = {
  'all':              { label: 'All' },
  'security-web3':    { label: 'Security & Web3' },
  'development':      { label: 'Dev' },
  'design-creative':  { label: 'Design & Creative' },
  'marketing-growth': { label: 'Marketing' },
  'cro-product':      { label: 'CRO & Product' },
  'ai-agents':        { label: 'AI & Agents' },
  'tools-utilities':  { label: 'Tools' },
};

window.TIERS = {
  legendary: { label: 'Legendary', color: '#FFD700', order: 0 },
  advanced:  { label: 'Advanced',  color: '#a855f7', order: 1 },
  standard:  { label: 'Standard',  color: '#3b82f6', order: 2 },
  noise:     { label: 'Noise',     color: '#444444', order: 3 },
};

window.SKILLS = [
  // ═══════════════════════════════════════════
  //  LEGENDARY TIER
  // ═══════════════════════════════════════════
  {
    id: 'vibecoding',
    name: 'Vibecoding',
    trigger: 'vibecoding',
    description: 'Master vibecoding methodology. Research → Plan → Build → Test workflow with parallel agents.',
    bundle: 'development',
    tier: 'legendary',
    grimoire_ready: true,
    source: 'claude-skill',
    status: 'active',
    keywords: ['coding', 'workflow', 'session', 'planning', 'worktree'],
  },
  {
    id: 'bounty-hunting',
    name: 'Bounty Hunting',
    trigger: 'bounty-hunting',
    description: 'Smart contract security audit methodology for bug bounties on Cantina, Immunefi, Code4rena. Pre-submission checklist, PoC templates, report writing.',
    bundle: 'security-web3',
    tier: 'legendary',
    grimoire_ready: true,
    source: 'claude-skill',
    status: 'active',
    keywords: ['bounty', 'security', 'audit', 'smart contract', 'cantina', 'immunefi', 'code4rena'],
  },
  {
    id: 'deep-research',
    name: 'Deep Research',
    trigger: '/deepsearch',
    description: 'Multi-step research with planning, decomposition, and long-context reasoning across tools and files.',
    bundle: 'ai-agents',
    tier: 'legendary',
    grimoire_ready: true,
    source: 'claude-skill',
    status: 'active',
    keywords: ['research', 'search', 'analysis', 'deep dive', 'synthesis'],
  },
  {
    id: 'crypto-merch-art',
    name: 'Crypto Merch Art',
    trigger: '/crypto-merch-art',
    description: 'Contest-specific art direction for RedotPay x Superteam Brasil. Archived — too narrow for general use. Kept internally.',
    bundle: 'design-creative',
    tier: 'standard',
    grimoire_ready: false,
    source: 'aria-custom',
    status: 'archived',
    keywords: ['merch', 'illustration', 'streetwear', 'crypto art', 'midjourney', 'character design', 'superteam'],
  },
  {
    id: 'merch-production',
    name: 'Merch Production by Marco',
    trigger: '/merch-production',
    description: 'Marco is a senior designer who takes AI-generated PNGs to print-ready production files. Rohit 3-level system: quick start → full 9-step workflow → reference library. Vectorization, AI text replacement, human-touch post-processing, color reduction, scale testing, export. The skill that bridges "cool AI image" and "real thing you can wear." v2.0 with full Rohit architecture.',
    bundle: 'design-creative',
    tier: 'advanced',
    grimoire_ready: true,
    source: 'aria-custom',
    status: 'active',
    keywords: ['merch', 'vector', 'figma', 'production', 'screen print', 'print-ready', 'marco', 'human-touch', 'font replacement'],
  },
  {
    id: 'blog-post-writer',
    name: 'Blog Post Writer',
    trigger: '/blog-post-writer',
    description: 'Universal blog post pipeline for writers, PMs, and founders. Six stages: Aria interviews you about the topic → researches social pulse + articles → writes a brain dump draft in your natural voice → captures your voice reaction (WisprFlow/Whisper/text) → clones your brand voice from past articles → humanizer pass. Works for any company, any topic, any writer. First-time-user ready. v2.0 Legendary.',
    bundle: 'marketing-growth',
    tier: 'legendary',
    grimoire_ready: true,
    source: 'aria-custom',
    status: 'active',
    keywords: ['blog post', 'writing', 'voice clone', 'wisprflow', 'humanizer', 'publication', 'style steal', 'interview', 'content'],
  },
  {
    id: 'senior-dev-review',
    name: 'Senior Dev Review (Marcus Mode)',
    trigger: '/senior-dev-review',
    description: 'Reviews AI-generated or vibe-coded code as a senior production engineer would. Not "does it work?" but "what happens when things goes wrong?" Eight review categories: circuit breakers, error differentiation, retry behavior, observability, graceful degradation, happy path gaps, load/race conditions, security assumptions. Output includes a 3 AM scenario and production-ready score. Based on a real $12,400 AWS incident. v1.0 Legendary.',
    bundle: 'development',
    tier: 'legendary',
    grimoire_ready: true,
    source: 'aria-custom',
    status: 'active',
    keywords: ['code review', 'production', 'reliability', 'circuit breaker', 'senior dev', 'marcus', 'ai code', 'vibe coding', 'incident'],
  },
  {
    id: 'obsidian-agent-os',
    name: 'Obsidian Agent OS',
    trigger: '/obsidian-agent-os',
    description: 'Build a 24/7 personal OS in Obsidian wired to AI agents. Three modes: SETUP (vault architecture for agent synergy), COMPRESS (NotebookLM + YouTube extension + Book Filter pipeline for 10x faster learning), VOICE (extract any publication\'s writing style and apply it to your draft). Includes 7 slash commands (/context, /trace, /ghost, /connect, /ideas, /graduate, /emerge), WisprFlow brain dump workflow, full humanizer pass, and vault health validator. v1.0 — Legendary. Sources: Greg Isenberg, polydao, Rohit, internetVin, AtlasForgeAI.',
    bundle: 'ai-agents',
    tier: 'legendary',
    grimoire_ready: true,
    source: 'aria-custom',
    status: 'active',
    keywords: ['obsidian', 'notebooklm', 'second brain', 'personal os', 'knowledge management', 'writing voice', 'wisprflow', 'slash commands', 'learning', 'blog post'],
  },
  {
    id: 'social-crypto-legend',
    name: 'Social Crypto Legend',
    trigger: '/social-crypto-legend',
    description: 'Legendary social writing brain for crypto builders on X. v2.0: voice-memo flow + humanizer 24-pattern kill list + soul check pass (the step most writing tools skip) + Rohit 3-level architecture. Ships sneak peeks, contest entries, and build-in-public moments that sound like a real person wrote them. No hashtags. Ever. Validated on a live Superteam contest.',
    bundle: 'marketing-growth',
    tier: 'legendary',
    grimoire_ready: true,
    source: 'aria-custom',
    status: 'active',
    keywords: ['twitter', 'x', 'social', 'tweet', 'voice memo', 'build in public', 'crypto writing', 'humanizer', 'soul check', 'contest'],
  },
  {
    id: 'humanizer',
    name: 'Humanizer',
    trigger: '"humanize text"',
    description: 'Strip AI writing patterns from text. Make prose sound natural and human-written. Run on any user-facing content before sending.',
    bundle: 'design-creative',
    tier: 'legendary',
    grimoire_ready: true,
    source: 'openclaw',
    status: 'active',
    keywords: ['writing', 'ai-detection', 'editing', 'prose', 'natural'],
  },

  // ═══════════════════════════════════════════
  //  ADVANCED TIER
  // ═══════════════════════════════════════════
  {
    id: 'dev-solidity',
    name: 'Solidity Dev',
    trigger: 'dev-solidity',
    description: 'EVM development with Solidity, Foundry, and security patterns. For Ethereum, Base, and L2 builds.',
    bundle: 'security-web3',
    tier: 'advanced',
    grimoire_ready: true,
    source: 'claude-skill',
    status: 'active',
    keywords: ['solidity', 'evm', 'ethereum', 'foundry', 'smart contract', 'defi', 'base'],
  },
  {
    id: 'dev-solana',
    name: 'Solana Dev',
    trigger: 'dev-solana',
    description: 'Solana development with Anchor, Pinocchio, and security patterns. For hackathons and audits.',
    bundle: 'security-web3',
    tier: 'advanced',
    grimoire_ready: true,
    source: 'claude-skill',
    status: 'active',
    keywords: ['solana', 'anchor', 'rust', 'pinocchio', 'spl', 'token-2022', 'hackathon'],
  },
  {
    id: 'solidity-security',
    name: 'Solidity Security',
    trigger: '/solidity-security',
    description: 'Smart contract security patterns for Solidity. Reentrancy, overflow, access control, and EVM-specific vulnerabilities.',
    bundle: 'security-web3',
    tier: 'advanced',
    grimoire_ready: true,
    source: 'antigravity',
    status: 'active',
    keywords: ['security', 'solidity', 'smart-contracts', 'evm', 'defi'],
  },
  {
    id: 'vulnerability-scanner',
    name: 'Vulnerability Scanner',
    trigger: '/vulnerability-scanner',
    description: 'Advanced vulnerability analysis and scanning patterns for identifying security weaknesses.',
    bundle: 'security-web3',
    tier: 'advanced',
    grimoire_ready: true,
    source: 'antigravity',
    status: 'active',
    keywords: ['security', 'vulnerability', 'scanning', 'analysis'],
  },
  {
    id: 'media-gen',
    name: 'Media Gen',
    trigger: 'media-gen',
    description: 'AI image and video generation with Nano Banana (Gemini), Veo 3, Midjourney, and more.',
    bundle: 'design-creative',
    tier: 'advanced',
    grimoire_ready: true,
    source: 'claude-skill',
    status: 'active',
    keywords: ['image', 'video', 'generation', 'midjourney', 'gemini', 'veo', 'ai art'],
  },
  {
    id: 'ui-ux-pro-max',
    name: 'UI/UX Pro Max',
    trigger: '/ui-ux-pro-max',
    description: 'Premium design systems and tokens. Advanced patterns for beautiful, accessible, production-ready UIs.',
    bundle: 'development',
    tier: 'advanced',
    grimoire_ready: true,
    source: 'antigravity',
    status: 'active',
    keywords: ['design', 'ui', 'ux', 'design-system', 'tokens', 'accessibility'],
  },
  {
    id: 'advisory-council',
    name: 'Advisory Council',
    trigger: 'advisory-council',
    description: 'Multi-persona analysis system. Get parallel perspectives from independent AI experts on any problem.',
    bundle: 'ai-agents',
    tier: 'advanced',
    grimoire_ready: true,
    source: 'claude-skill',
    status: 'active',
    keywords: ['multi-persona', 'analysis', 'perspectives', 'experts', 'council'],
  },
  {
    id: 'marketing',
    name: 'Marketing',
    trigger: 'marketing',
    description: 'GTM strategy, copywriting, content creation with recursive self-improvement loops.',
    bundle: 'marketing-growth',
    tier: 'advanced',
    grimoire_ready: true,
    source: 'claude-skill',
    status: 'active',
    keywords: ['gtm', 'strategy', 'copywriting', 'content', 'growth'],
  },
  {
    id: 'product-manager-toolkit',
    name: 'PM Toolkit',
    trigger: '/product-manager-toolkit',
    description: 'RICE prioritization, PRD templates, roadmap planning, and product strategy frameworks for PMs.',
    bundle: 'cro-product',
    tier: 'advanced',
    grimoire_ready: true,
    source: 'antigravity',
    status: 'active',
    keywords: ['product', 'pm', 'rice', 'prd', 'roadmap', 'prioritization'],
  },
  {
    id: 'prompt-engineering',
    name: 'Prompt Engineering',
    trigger: '/prompt-engineering',
    description: 'Master the art of talking to LLMs. Structured prompting, chain-of-thought, few-shot, and system design.',
    bundle: 'ai-agents',
    tier: 'advanced',
    grimoire_ready: true,
    source: 'antigravity',
    status: 'active',
    keywords: ['prompts', 'llm', 'ai', 'chain-of-thought', 'few-shot'],
  },
  {
    id: 'nextjs-best-practices',
    name: 'Next.js Best Practices',
    trigger: '/nextjs-best-practices',
    description: 'Next.js 15+ App Router patterns. Server components, caching, streaming, and performance optimization.',
    bundle: 'development',
    tier: 'advanced',
    grimoire_ready: false,
    source: 'antigravity',
    status: 'active',
    keywords: ['nextjs', 'react', 'app-router', 'frontend', 'performance'],
  },
  {
    id: 'systematic-debugging',
    name: 'Systematic Debugging',
    trigger: '/systematic-debugging',
    description: 'Debug like a pro. Structured approach to isolating, reproducing, and fixing bugs systematically.',
    bundle: 'development',
    tier: 'advanced',
    grimoire_ready: false,
    source: 'antigravity',
    status: 'active',
    keywords: ['debugging', 'errors', 'troubleshooting', 'systematic'],
  },
  {
    id: 'competitive-landscape',
    name: 'Competitive Landscape',
    trigger: '/competitive-landscape',
    description: 'Competitor analysis framework. Map the landscape, identify positioning gaps, and find strategic opportunities.',
    bundle: 'marketing-growth',
    tier: 'advanced',
    grimoire_ready: false,
    source: 'antigravity',
    status: 'active',
    keywords: ['research', 'competitors', 'analysis', 'positioning', 'strategy'],
  },
  {
    id: 'startup-metrics-framework',
    name: 'Startup Metrics',
    trigger: '/startup-metrics-framework',
    description: 'SaaS metrics and unit economics. ARR, churn, LTV, CAC, and the metrics that actually matter.',
    bundle: 'marketing-growth',
    tier: 'advanced',
    grimoire_ready: false,
    source: 'antigravity',
    status: 'active',
    keywords: ['startup', 'metrics', 'saas', 'arr', 'ltv', 'cac', 'analytics'],
  },

  // ═══════════════════════════════════════════
  //  STANDARD TIER — Security & Web3
  // ═══════════════════════════════════════════
  {
    id: 'security-review',
    name: 'Security Review',
    trigger: 'security-review',
    description: 'Comprehensive security checklist for auth, user input, secrets, API endpoints, and payment features.',
    bundle: 'security-web3',
    tier: 'standard',
    grimoire_ready: false,
    source: 'ecc',
    status: 'active',
    keywords: ['security', 'auth', 'owasp', 'checklist', 'review', 'vulnerabilities'],
  },
  {
    id: 'security-auditor',
    name: 'Security Auditor',
    trigger: '/security-auditor',
    description: 'Comprehensive security audits. Systematic review of codebases, configs, and infrastructure.',
    bundle: 'security-web3',
    tier: 'standard',
    grimoire_ready: false,
    source: 'antigravity',
    status: 'active',
    keywords: ['security', 'audit', 'review', 'codebase', 'infrastructure'],
  },
  {
    id: 'blockchain-developer',
    name: 'Blockchain Developer',
    trigger: '/blockchain-developer',
    description: 'Full-stack blockchain development patterns. Smart contracts, wallets, transactions, and onchain data.',
    bundle: 'security-web3',
    tier: 'standard',
    grimoire_ready: false,
    source: 'antigravity',
    status: 'active',
    keywords: ['blockchain', 'web3', 'smart-contracts', 'wallets', 'crypto'],
  },
  {
    id: 'defi-protocol-templates',
    name: 'DeFi Protocol Templates',
    trigger: '/defi-protocol-templates',
    description: 'DeFi protocol implementation templates. AMMs, lending, staking, yield farming, and governance patterns.',
    bundle: 'security-web3',
    tier: 'standard',
    grimoire_ready: false,
    source: 'antigravity',
    status: 'active',
    keywords: ['defi', 'amm', 'lending', 'staking', 'yield', 'governance', 'solidity'],
  },

  // ═══════════════════════════════════════════
  //  STANDARD TIER — Development
  // ═══════════════════════════════════════════
  {
    id: 'frontend-patterns',
    name: 'Frontend Patterns',
    trigger: 'frontend-patterns',
    description: 'React and Next.js patterns, state management, performance optimization, and UI best practices.',
    bundle: 'development',
    tier: 'standard',
    grimoire_ready: false,
    source: 'ecc',
    status: 'active',
    keywords: ['react', 'nextjs', 'frontend', 'ui', 'state', 'performance', 'patterns'],
  },
  {
    id: 'backend-patterns',
    name: 'Backend Patterns',
    trigger: 'backend-patterns',
    description: 'API design, database optimization, and server-side patterns for Node.js, Express, and Next.js API routes.',
    bundle: 'development',
    tier: 'standard',
    grimoire_ready: false,
    source: 'ecc',
    status: 'active',
    keywords: ['api', 'backend', 'nodejs', 'express', 'nextjs', 'server', 'patterns'],
  },
  {
    id: 'postgres-patterns',
    name: 'Postgres Patterns',
    trigger: 'postgres-patterns',
    description: 'PostgreSQL query optimization, schema design, indexing, and security. Based on Supabase best practices.',
    bundle: 'development',
    tier: 'standard',
    grimoire_ready: false,
    source: 'ecc',
    status: 'active',
    keywords: ['postgres', 'postgresql', 'supabase', 'database', 'sql', 'query', 'indexing'],
  },
  {
    id: 'supabase-automation',
    name: 'Supabase Automation',
    trigger: '/supabase-automation',
    description: 'Automate Supabase workflows. Schema migrations, RLS policies, Edge Functions, and storage management.',
    bundle: 'development',
    tier: 'standard',
    grimoire_ready: false,
    source: 'antigravity',
    status: 'active',
    keywords: ['supabase', 'postgres', 'database', 'rls', 'automation'],
  },
  {
    id: 'react-dev',
    name: 'React Dev',
    trigger: '"react component"',
    description: 'Build React components with TypeScript. Covers type-safe patterns for React 18-19.',
    bundle: 'development',
    tier: 'standard',
    grimoire_ready: false,
    source: 'openclaw',
    status: 'active',
    keywords: ['react', 'typescript', 'components', 'frontend'],
  },
  {
    id: 'react-useeffect',
    name: 'React useEffect',
    trigger: '"useEffect help"',
    description: 'React useEffect best practices from official docs. When NOT to use Effect and better alternatives.',
    bundle: 'development',
    tier: 'standard',
    grimoire_ready: false,
    source: 'openclaw',
    status: 'active',
    keywords: ['react', 'hooks', 'useeffect', 'frontend'],
  },
  {
    id: 'design-system-starter',
    name: 'Design System Starter',
    trigger: '"create design system"',
    description: 'Create and evolve design systems with design tokens, component architecture, and accessibility guidelines.',
    bundle: 'development',
    tier: 'standard',
    grimoire_ready: false,
    source: 'openclaw',
    status: 'active',
    keywords: ['design', 'frontend', 'design-system', 'tokens', 'accessibility'],
  },
  {
    id: 'mui',
    name: 'Material-UI v7',
    trigger: '"mui" / "material ui"',
    description: 'Material-UI v7 component library patterns including sx prop styling, theme integration, and responsive design.',
    bundle: 'development',
    tier: 'standard',
    grimoire_ready: false,
    source: 'openclaw',
    status: 'active',
    keywords: ['mui', 'material-ui', 'react', 'frontend'],
  },
  {
    id: 'openapi-to-typescript',
    name: 'OpenAPI to TypeScript',
    trigger: '"convert openapi"',
    description: 'Converts OpenAPI 3.0 JSON/YAML to TypeScript interfaces and type guards.',
    bundle: 'development',
    tier: 'standard',
    grimoire_ready: false,
    source: 'openclaw',
    status: 'active',
    keywords: ['openapi', 'typescript', 'api', 'frontend'],
  },
  {
    id: 'database-schema-designer',
    name: 'Database Schema Designer',
    trigger: '"design schema" / "database design"',
    description: 'Design robust, scalable database schemas for SQL and NoSQL. Normalization, indexing, migration patterns.',
    bundle: 'development',
    tier: 'standard',
    grimoire_ready: false,
    source: 'openclaw',
    status: 'active',
    keywords: ['database', 'schema', 'sql', 'nosql'],
  },
  {
    id: 'naming-analyzer',
    name: 'Naming Analyzer',
    trigger: '"suggest names" / "rename"',
    description: 'Suggest better variable, function, and class names based on context and conventions.',
    bundle: 'development',
    tier: 'standard',
    grimoire_ready: false,
    source: 'openclaw',
    status: 'active',
    keywords: ['naming', 'refactoring', 'code-quality'],
  },
  {
    id: 'reducing-entropy',
    name: 'Reducing Entropy',
    trigger: '"reduce entropy" / "minimize code"',
    description: 'Minimize total codebase size. Manual-only. Measures success by final code amount.',
    bundle: 'development',
    tier: 'standard',
    grimoire_ready: false,
    source: 'openclaw',
    status: 'active',
    keywords: ['refactoring', 'cleanup', 'code-size'],
  },
  {
    id: 'review-loop',
    name: 'Review Loop',
    trigger: '/review-loop',
    description: 'Implement task, get independent Codex review, address feedback in a structured loop.',
    bundle: 'development',
    tier: 'standard',
    grimoire_ready: false,
    source: 'claude-plugin',
    status: 'active',
    keywords: ['review', 'code review', 'feedback', 'codex'],
  },

  // ═══════════════════════════════════════════
  //  STANDARD TIER — Design & Creative
  // ═══════════════════════════════════════════
  {
    id: 'agent-ui-ux-designer',
    name: 'UI/UX Design Critic',
    trigger: '"review UI" / "UX feedback"',
    description: 'Expert UI/UX design critic and advisor. Research-backed, opinionated feedback on interfaces.',
    bundle: 'design-creative',
    tier: 'standard',
    grimoire_ready: false,
    source: 'openclaw',
    status: 'active',
    keywords: ['ui', 'ux', 'design', 'feedback', 'critique'],
  },
  {
    id: 'card-art-grimoire',
    name: 'Card Art — Grimoire',
    trigger: '"card art" / "tier card" / "mtg style"',
    description: 'Generate MTG-style tier card art for Agent Grimoire. Uses the real Magic: The Gathering illustration system.',
    bundle: 'design-creative',
    tier: 'standard',
    grimoire_ready: false,
    source: 'claude-skill',
    status: 'active',
    keywords: ['card art', 'mtg', 'magic the gathering', 'tier card', 'image generation'],
  },
  {
    id: 'video-pipeline',
    name: 'Video Pipeline',
    trigger: 'video-pipeline',
    description: 'Video creation pipeline with Remotion, HeyGen, demo recording, and automation.',
    bundle: 'design-creative',
    tier: 'standard',
    grimoire_ready: false,
    source: 'claude-skill',
    status: 'active',
    keywords: ['video', 'remotion', 'heygen', 'recording', 'automation'],
  },

  // ═══════════════════════════════════════════
  //  STANDARD TIER — Marketing & Growth
  // ═══════════════════════════════════════════
  {
    id: 'content-strategy',
    name: 'Content Strategy',
    trigger: 'content-strategy',
    description: 'Plan content strategy, decide what to create, and figure out topics to cover for growth.',
    bundle: 'marketing-growth',
    tier: 'standard',
    grimoire_ready: false,
    source: 'claude-skill',
    status: 'active',
    keywords: ['content', 'strategy', 'topics', 'planning', 'growth'],
  },
  {
    id: 'social-content',
    name: 'Social Content',
    trigger: 'social-content',
    description: 'Create, schedule, and optimize social media content for LinkedIn, Twitter/X, Instagram, and TikTok.',
    bundle: 'marketing-growth',
    tier: 'standard',
    grimoire_ready: false,
    source: 'claude-skill',
    status: 'active',
    keywords: ['social media', 'linkedin', 'twitter', 'instagram', 'tiktok'],
  },
  {
    id: 'copywriting',
    name: 'Copywriting',
    trigger: 'copywriting',
    description: 'Write, rewrite, or improve marketing copy for homepages, landing pages, pricing pages, and product pages.',
    bundle: 'marketing-growth',
    tier: 'standard',
    grimoire_ready: false,
    source: 'claude-skill',
    status: 'active',
    keywords: ['copy', 'writing', 'landing page', 'marketing', 'conversion'],
  },
  {
    id: 'email-sequence',
    name: 'Email Sequence',
    trigger: 'email-sequence',
    description: 'Create or optimize email sequences, drip campaigns, automated flows, and lifecycle emails.',
    bundle: 'marketing-growth',
    tier: 'standard',
    grimoire_ready: false,
    source: 'claude-skill',
    status: 'active',
    keywords: ['email', 'drip', 'nurture', 'sequence', 'automation'],
  },
  {
    id: 'paid-ads',
    name: 'Paid Ads',
    trigger: 'paid-ads',
    description: 'Paid advertising campaigns on Google Ads, Meta, LinkedIn, and Twitter/X. Ad copy, targeting, and optimization.',
    bundle: 'marketing-growth',
    tier: 'standard',
    grimoire_ready: false,
    source: 'claude-skill',
    status: 'active',
    keywords: ['ppc', 'ads', 'google', 'meta', 'linkedin', 'paid media'],
  },
  {
    id: 'programmatic-seo',
    name: 'Programmatic SEO',
    trigger: 'programmatic-seo',
    description: 'Create SEO-driven pages at scale using templates and data. Directory, location, and keyword pages.',
    bundle: 'marketing-growth',
    tier: 'standard',
    grimoire_ready: false,
    source: 'claude-skill',
    status: 'active',
    keywords: ['seo', 'programmatic', 'templates', 'directory', 'scale'],
  },
  {
    id: 'launch-strategy',
    name: 'Launch Strategy',
    trigger: 'launch-strategy',
    description: 'Plan product launches, feature announcements, and release strategies including Product Hunt.',
    bundle: 'marketing-growth',
    tier: 'standard',
    grimoire_ready: false,
    source: 'claude-skill',
    status: 'active',
    keywords: ['launch', 'product hunt', 'release', 'announcement', 'go-to-market'],
  },
  {
    id: 'free-tool-strategy',
    name: 'Free Tool Strategy',
    trigger: 'free-tool-strategy',
    description: 'Plan and build free tools for marketing — lead generation, SEO value, and brand awareness.',
    bundle: 'marketing-growth',
    tier: 'standard',
    grimoire_ready: false,
    source: 'claude-skill',
    status: 'active',
    keywords: ['free tool', 'engineering as marketing', 'lead gen', 'seo'],
  },
  {
    id: 'pricing-strategy',
    name: 'Pricing Strategy',
    trigger: 'pricing-strategy',
    description: 'Pricing decisions, packaging, monetization strategy. Freemium, trials, tiers, and value metrics.',
    bundle: 'marketing-growth',
    tier: 'standard',
    grimoire_ready: false,
    source: 'claude-skill',
    status: 'active',
    keywords: ['pricing', 'freemium', 'tiers', 'monetization', 'packaging'],
  },
  {
    id: 'referral-program',
    name: 'Referral Program',
    trigger: 'referral-program',
    description: 'Create and optimize referral programs, affiliate programs, and word-of-mouth strategies.',
    bundle: 'marketing-growth',
    tier: 'standard',
    grimoire_ready: false,
    source: 'claude-skill',
    status: 'active',
    keywords: ['referral', 'affiliate', 'word of mouth', 'viral', 'ambassador'],
  },
  {
    id: 'market-sizing-analysis',
    name: 'Market Sizing',
    trigger: '/market-sizing-analysis',
    description: 'TAM/SAM/SOM calculations and market sizing methodology for pitches and strategic planning.',
    bundle: 'marketing-growth',
    tier: 'standard',
    grimoire_ready: false,
    source: 'antigravity',
    status: 'active',
    keywords: ['market', 'tam', 'sam', 'som', 'sizing', 'analysis'],
  },
  {
    id: 'marketing-ideas',
    name: 'Marketing Ideas',
    trigger: 'marketing-ideas',
    description: 'Marketing ideas, inspiration, and strategies for SaaS and software products.',
    bundle: 'marketing-growth',
    tier: 'standard',
    grimoire_ready: false,
    source: 'claude-skill',
    status: 'active',
    keywords: ['marketing', 'ideas', 'growth', 'strategies', 'inspiration'],
  },
  {
    id: 'marketing-psychology',
    name: 'Marketing Psychology',
    trigger: 'marketing-psychology',
    description: 'Apply psychological principles, mental models, and behavioral science to marketing.',
    bundle: 'marketing-growth',
    tier: 'standard',
    grimoire_ready: false,
    source: 'claude-skill',
    status: 'active',
    keywords: ['psychology', 'mental models', 'cognitive bias', 'persuasion', 'behavior'],
  },
  {
    id: 'competitor-alternatives',
    name: 'Competitor Alternatives',
    trigger: 'competitor-alternatives',
    description: 'Create competitor comparison and alternative pages for SEO and sales enablement.',
    bundle: 'marketing-growth',
    tier: 'standard',
    grimoire_ready: false,
    source: 'claude-skill',
    status: 'active',
    keywords: ['competitor', 'alternatives', 'comparison', 'vs page', 'seo'],
  },

  // ═══════════════════════════════════════════
  //  STANDARD TIER — CRO & Product
  // ═══════════════════════════════════════════
  {
    id: 'form-cro',
    name: 'Form CRO',
    trigger: 'form-cro',
    description: 'Optimize lead capture, contact, demo request, application, and checkout forms for conversion.',
    bundle: 'cro-product',
    tier: 'standard',
    grimoire_ready: false,
    source: 'claude-skill',
    status: 'active',
    keywords: ['form', 'cro', 'conversion', 'lead capture', 'optimization'],
  },
  {
    id: 'page-cro',
    name: 'Page CRO',
    trigger: 'page-cro',
    description: 'Optimize any marketing page for conversions — homepage, landing pages, pricing, feature pages.',
    bundle: 'cro-product',
    tier: 'standard',
    grimoire_ready: false,
    source: 'claude-skill',
    status: 'active',
    keywords: ['page', 'cro', 'conversion', 'landing page', 'optimization'],
  },
  {
    id: 'signup-flow-cro',
    name: 'Signup Flow CRO',
    trigger: 'signup-flow-cro',
    description: 'Optimize signup, registration, account creation, and trial activation flows.',
    bundle: 'cro-product',
    tier: 'standard',
    grimoire_ready: false,
    source: 'claude-skill',
    status: 'active',
    keywords: ['signup', 'registration', 'trial', 'activation', 'cro'],
  },
  {
    id: 'onboarding-cro',
    name: 'Onboarding CRO',
    trigger: 'onboarding-cro',
    description: 'Optimize post-signup onboarding, user activation, first-run experience, and time-to-value.',
    bundle: 'cro-product',
    tier: 'standard',
    grimoire_ready: false,
    source: 'claude-skill',
    status: 'active',
    keywords: ['onboarding', 'activation', 'first-run', 'time-to-value', 'cro'],
  },
  {
    id: 'paywall-upgrade-cro',
    name: 'Paywall Upgrade CRO',
    trigger: 'paywall-upgrade-cro',
    description: 'Create or optimize in-app paywalls, upgrade screens, upsell modals, and feature gates.',
    bundle: 'cro-product',
    tier: 'standard',
    grimoire_ready: false,
    source: 'claude-skill',
    status: 'active',
    keywords: ['paywall', 'upgrade', 'upsell', 'feature gate', 'cro'],
  },
  {
    id: 'popup-cro',
    name: 'Popup CRO',
    trigger: 'popup-cro',
    description: 'Create or optimize popups, modals, overlays, slide-ins, and banners for conversion.',
    bundle: 'cro-product',
    tier: 'standard',
    grimoire_ready: false,
    source: 'claude-skill',
    status: 'active',
    keywords: ['popup', 'modal', 'exit intent', 'overlay', 'cro'],
  },
  {
    id: 'ab-test-setup',
    name: 'A/B Test Setup',
    trigger: 'ab-test-setup',
    description: 'Plan, design, and implement A/B tests and experiments with variant copy and analysis.',
    bundle: 'cro-product',
    tier: 'standard',
    grimoire_ready: false,
    source: 'claude-skill',
    status: 'active',
    keywords: ['ab test', 'split test', 'experiment', 'variant', 'cro'],
  },
  {
    id: 'analytics-tracking',
    name: 'Analytics Tracking',
    trigger: 'analytics-tracking',
    description: 'Set up and audit analytics tracking — GA4, conversion tracking, event tracking, UTM parameters.',
    bundle: 'cro-product',
    tier: 'standard',
    grimoire_ready: false,
    source: 'claude-skill',
    status: 'active',
    keywords: ['analytics', 'ga4', 'tracking', 'conversion', 'utm'],
  },
  {
    id: 'schema-markup',
    name: 'Schema Markup',
    trigger: 'schema-markup',
    description: 'Add, fix, or optimize schema markup and structured data. JSON-LD, rich snippets, FAQ schema.',
    bundle: 'cro-product',
    tier: 'standard',
    grimoire_ready: false,
    source: 'claude-skill',
    status: 'active',
    keywords: ['schema', 'structured data', 'json-ld', 'rich snippets', 'seo'],
  },
  {
    id: 'product-marketing-context',
    name: 'Product Marketing Context',
    trigger: 'product-marketing-context',
    description: 'Create or update product marketing context documents — positioning, messaging, and audience.',
    bundle: 'cro-product',
    tier: 'standard',
    grimoire_ready: false,
    source: 'claude-skill',
    status: 'active',
    keywords: ['product', 'marketing', 'context', 'positioning', 'messaging'],
  },

  // ═══════════════════════════════════════════
  //  STANDARD TIER — AI & Agents
  // ═══════════════════════════════════════════
  {
    id: 'mcp-builder',
    name: 'MCP Builder',
    trigger: '/mcp-builder',
    description: 'Create your own MCP tools. Build, test, and publish Model Context Protocol servers for Claude.',
    bundle: 'ai-agents',
    tier: 'standard',
    grimoire_ready: false,
    source: 'antigravity',
    status: 'active',
    keywords: ['mcp', 'tools', 'claude', 'protocol', 'agents', 'builder'],
  },
  {
    id: 'brainstorming',
    name: 'Brainstorming',
    trigger: '/brainstorming',
    description: 'Multi-perspective brainstorming for ideas, MVPs, and creative problem solving.',
    bundle: 'ai-agents',
    tier: 'standard',
    grimoire_ready: false,
    source: 'antigravity',
    status: 'active',
    keywords: ['brainstorming', 'ideas', 'mvp', 'creativity', 'planning'],
  },
  {
    id: 'continuous-learning-v2',
    name: 'Continuous Learning',
    trigger: 'continuous-learning-v2',
    description: 'Instinct-based learning that observes sessions, creates atomic instincts with confidence scoring, and evolves them into reusable skills.',
    bundle: 'ai-agents',
    tier: 'standard',
    grimoire_ready: false,
    source: 'ecc',
    status: 'active',
    keywords: ['learning', 'instincts', 'patterns', 'evolve', 'skills', 'memory'],
  },
  {
    id: 'concise-planning',
    name: 'Concise Planning',
    trigger: '/concise-planning',
    description: 'Always start with a plan. Structured task breakdown before writing a single line of code.',
    bundle: 'ai-agents',
    tier: 'standard',
    grimoire_ready: false,
    source: 'antigravity',
    status: 'active',
    keywords: ['planning', 'breakdown', 'tasks', 'workflow', 'pre-coding'],
  },
  {
    id: 'game-changing-features',
    name: 'Game-Changing Features',
    trigger: '"find 10x features"',
    description: 'Find 10x product opportunities and high-leverage improvements. Strategic product thinking.',
    bundle: 'ai-agents',
    tier: 'standard',
    grimoire_ready: false,
    source: 'openclaw',
    status: 'active',
    keywords: ['product', 'strategy', 'features', '10x'],
  },
  {
    id: 'gepetto',
    name: 'Gepetto Planner',
    trigger: '"create implementation plan"',
    description: 'Detailed, sectionized implementation plans through research, stakeholder interviews, and multi-LLM review.',
    bundle: 'ai-agents',
    tier: 'standard',
    grimoire_ready: false,
    source: 'openclaw',
    status: 'active',
    keywords: ['planning', 'implementation', 'analysis', 'research'],
  },
  {
    id: 'requirements-clarity',
    name: 'Requirements Clarity',
    trigger: '"clarify requirements"',
    description: 'Clarify ambiguous requirements through focused dialogue before implementation.',
    bundle: 'ai-agents',
    tier: 'standard',
    grimoire_ready: false,
    source: 'openclaw',
    status: 'active',
    keywords: ['requirements', 'clarity', 'communication'],
  },
  {
    id: 'ship-learn-next',
    name: 'Ship-Learn-Next',
    trigger: '"ship learn next"',
    description: 'Transform learning content (transcripts, articles, tutorials) into actionable implementation plans.',
    bundle: 'ai-agents',
    tier: 'standard',
    grimoire_ready: false,
    source: 'openclaw',
    status: 'active',
    keywords: ['learning', 'implementation', 'action-items'],
  },
  {
    id: 'agent-ascii-ui-mockup-generator',
    name: 'ASCII UI Mockup Generator',
    trigger: '"create UI mockup" / "ascii mockup"',
    description: 'Visualize UI concepts through ASCII mockups before implementation. Multiple variations.',
    bundle: 'ai-agents',
    tier: 'standard',
    grimoire_ready: false,
    source: 'openclaw',
    status: 'active',
    keywords: ['ui', 'mockups', 'ascii', 'visualization'],
  },
  {
    id: 'agent-codebase-pattern-finder',
    name: 'Codebase Pattern Finder',
    trigger: '"find patterns" / "show examples"',
    description: 'Find similar implementations, usage examples, or existing patterns in the codebase.',
    bundle: 'ai-agents',
    tier: 'standard',
    grimoire_ready: false,
    source: 'openclaw',
    status: 'active',
    keywords: ['codebase', 'patterns', 'search', 'examples'],
  },
  {
    id: 'agent-communication-excellence-coach',
    name: 'Communication Coach',
    trigger: '"review draft" / "coach communication"',
    description: 'Review communication drafts. Email refinement, tone calibration, roleplay practice.',
    bundle: 'ai-agents',
    tier: 'standard',
    grimoire_ready: false,
    source: 'openclaw',
    status: 'active',
    keywords: ['communication', 'email', 'coaching'],
  },
  {
    id: 'agent-general-purpose',
    name: 'General Purpose Agent',
    trigger: 'auto-delegated',
    description: 'Default agent for handling complex, multi-step tasks with automatic delegation.',
    bundle: 'ai-agents',
    tier: 'standard',
    grimoire_ready: false,
    source: 'openclaw',
    status: 'active',
    keywords: ['general', 'delegation', 'tasks'],
  },
  {
    id: 'agent-mermaid-diagram-specialist',
    name: 'Mermaid Diagram Specialist',
    trigger: '"diagram specialist"',
    description: 'Mermaid diagram specialist for flowcharts, sequence diagrams, ERDs, and architecture.',
    bundle: 'ai-agents',
    tier: 'standard',
    grimoire_ready: false,
    source: 'openclaw',
    status: 'active',
    keywords: ['mermaid', 'diagrams', 'visualization'],
  },
  {
    id: 'codex',
    name: 'Codex (GPT-5.2)',
    trigger: '"codex exec" / "run codex"',
    description: 'Run Codex CLI for code analysis, refactoring, or automated editing. Uses GPT-5.2.',
    bundle: 'ai-agents',
    tier: 'standard',
    grimoire_ready: false,
    source: 'openclaw',
    status: 'active',
    keywords: ['ai', 'code-analysis', 'gpt', 'codex', 'openai'],
  },
  {
    id: 'gemini',
    name: 'Gemini (Large Context)',
    trigger: '"run gemini" / "gemini review"',
    description: 'Run Gemini CLI for code review, plan review, or big context (>200k) processing. Uses Gemini 3 Pro.',
    bundle: 'ai-agents',
    tier: 'standard',
    grimoire_ready: false,
    source: 'openclaw',
    status: 'active',
    keywords: ['ai', 'code-review', 'large-context', 'gemini', 'google'],
  },
  {
    id: 'perplexity',
    name: 'Perplexity Search',
    trigger: '"search" / "look up"',
    description: 'Web search and research using Perplexity AI for generic queries and latest information.',
    bundle: 'ai-agents',
    tier: 'standard',
    grimoire_ready: false,
    source: 'openclaw',
    status: 'active',
    keywords: ['ai', 'search', 'research', 'perplexity', 'web'],
  },

  // ═══════════════════════════════════════════
  //  STANDARD TIER — Tools & Utilities
  // ═══════════════════════════════════════════
  {
    id: 'vercel-deployment',
    name: 'Vercel Deployment',
    trigger: '/vercel-deployment',
    description: 'Deploy to Vercel like a pro. Zero-config deployments, env vars, preview URLs, and custom domains.',
    bundle: 'tools-utilities',
    tier: 'standard',
    grimoire_ready: false,
    source: 'antigravity',
    status: 'active',
    keywords: ['vercel', 'deployment', 'hosting', 'frontend', 'serverless'],
  },
  {
    id: 'commit-work',
    name: 'Commit Work',
    trigger: '"commit" / "stage changes"',
    description: 'Create high-quality git commits: review/stage changes, split into logical commits, clear messages.',
    bundle: 'tools-utilities',
    tier: 'standard',
    grimoire_ready: false,
    source: 'openclaw',
    status: 'active',
    keywords: ['git', 'commits', 'conventional-commits'],
  },
  {
    id: 'web-to-markdown',
    name: 'Web to Markdown',
    trigger: '"convert url" / "web to markdown"',
    description: 'Convert webpage URLs to clean Markdown via Puppeteer + Readability. Works with JS-rendered pages.',
    bundle: 'tools-utilities',
    tier: 'standard',
    grimoire_ready: false,
    source: 'openclaw',
    status: 'active',
    keywords: ['web', 'markdown', 'conversion'],
  },
  {
    id: 'domain-name-brainstormer',
    name: 'Domain Brainstormer',
    trigger: '"brainstorm domains"',
    description: 'Generate creative domain name ideas and check availability across multiple TLDs.',
    bundle: 'tools-utilities',
    tier: 'standard',
    grimoire_ready: false,
    source: 'openclaw',
    status: 'active',
    keywords: ['domains', 'naming', 'brainstorming'],
  },
  {
    id: 'meme-factory',
    name: 'Meme Factory',
    trigger: '"make a meme"',
    description: 'Generate memes using the memegen.link API. Visual aids for social media.',
    bundle: 'tools-utilities',
    tier: 'standard',
    grimoire_ready: false,
    source: 'openclaw',
    status: 'active',
    keywords: ['memes', 'images', 'social-media'],
  },
  {
    id: 'jira',
    name: 'Jira Integration',
    trigger: '"jira" / "PROJ-123"',
    description: 'Create/view/update Jira issues, check sprint status, manage workflow. Triggers on issue key patterns.',
    bundle: 'tools-utilities',
    tier: 'standard',
    grimoire_ready: false,
    source: 'openclaw',
    status: 'active',
    keywords: ['jira', 'tickets', 'project-management', 'atlassian'],
  },
  {
    id: 'keybindings-help',
    name: 'Keybindings Help',
    trigger: '"keybindings" / "shortcuts"',
    description: 'Customize keyboard shortcuts, rebind keys, add chord bindings, modify keybindings.json.',
    bundle: 'tools-utilities',
    tier: 'standard',
    grimoire_ready: false,
    source: 'system',
    status: 'active',
    keywords: ['keybindings', 'shortcuts', 'keyboard', 'configuration'],
  },
  // Documentation tools
  {
    id: 'c4-architecture',
    name: 'C4 Architecture',
    trigger: '"architecture diagram" / "C4 diagram"',
    description: 'Generate architecture documentation using C4 model Mermaid diagrams.',
    bundle: 'tools-utilities',
    tier: 'standard',
    grimoire_ready: false,
    source: 'openclaw',
    status: 'active',
    keywords: ['architecture', 'c4', 'mermaid', 'diagrams'],
  },
  {
    id: 'mermaid-diagrams',
    name: 'Mermaid Diagrams',
    trigger: '"create diagram" / "mermaid"',
    description: 'Comprehensive guide for creating software diagrams using Mermaid syntax.',
    bundle: 'tools-utilities',
    tier: 'standard',
    grimoire_ready: false,
    source: 'openclaw',
    status: 'active',
    keywords: ['diagrams', 'mermaid', 'visualization', 'flowchart'],
  },
  {
    id: 'excalidraw',
    name: 'Excalidraw',
    trigger: '"excalidraw"',
    description: 'Work with *.excalidraw files for diagrams, flowcharts, and architecture visualization.',
    bundle: 'tools-utilities',
    tier: 'standard',
    grimoire_ready: false,
    source: 'openclaw',
    status: 'active',
    keywords: ['diagrams', 'excalidraw', 'visualization'],
  },
  {
    id: 'draw-io',
    name: 'Draw.io Diagrams',
    trigger: '"draw.io" / "create drawio"',
    description: 'Draw.io diagram creation, editing, and review. Supports .drawio XML editing and PNG conversion.',
    bundle: 'tools-utilities',
    tier: 'standard',
    grimoire_ready: false,
    source: 'openclaw',
    status: 'active',
    keywords: ['diagrams', 'draw-io', 'xml'],
  },
  {
    id: 'marp-slide',
    name: 'Marp Slides',
    trigger: '"create slides" / "marp"',
    description: 'Create professional Marp presentation slides with 7 beautiful themes.',
    bundle: 'tools-utilities',
    tier: 'standard',
    grimoire_ready: false,
    source: 'openclaw',
    status: 'active',
    keywords: ['presentations', 'slides', 'marp'],
  },
  {
    id: 'crafting-effective-readmes',
    name: 'Crafting READMEs',
    trigger: '"write readme" / "improve readme"',
    description: 'Templates and guidance for writing READMEs matched to your audience and project type.',
    bundle: 'tools-utilities',
    tier: 'standard',
    grimoire_ready: false,
    source: 'openclaw',
    status: 'active',
    keywords: ['readme', 'writing', 'templates'],
  },
  {
    id: 'backend-to-frontend-handoff-docs',
    name: 'API Handoff Docs',
    trigger: '"create handoff docs"',
    description: 'Create API handoff documentation for frontend developers when backend work is complete.',
    bundle: 'tools-utilities',
    tier: 'standard',
    grimoire_ready: false,
    source: 'openclaw',
    status: 'active',
    keywords: ['api', 'handoff', 'frontend', 'backend'],
  },
  {
    id: 'frontend-to-backend-requirements',
    name: 'FE-to-BE Requirements',
    trigger: '"document frontend needs"',
    description: 'Document frontend data needs for backend developers. Communicate API requirements clearly.',
    bundle: 'tools-utilities',
    tier: 'standard',
    grimoire_ready: false,
    source: 'openclaw',
    status: 'active',
    keywords: ['api', 'requirements', 'frontend', 'backend'],
  },
  {
    id: 'writing-clearly-and-concisely',
    name: 'Writing Clearly',
    trigger: '"write clearly" / "improve writing"',
    description: 'Write prose humans will read — documentation, commit messages, error messages, UI text.',
    bundle: 'tools-utilities',
    tier: 'standard',
    grimoire_ready: false,
    source: 'openclaw',
    status: 'active',
    keywords: ['writing', 'communication', 'prose'],
  },
  // Professional tools
  {
    id: 'difficult-workplace-conversations',
    name: 'Difficult Conversations',
    trigger: '"difficult conversation"',
    description: 'Structured approach to workplace conflicts, performance discussions, and challenging feedback.',
    bundle: 'tools-utilities',
    tier: 'standard',
    grimoire_ready: false,
    source: 'openclaw',
    status: 'active',
    keywords: ['professional', 'communication', 'feedback', 'conflict'],
  },
  {
    id: 'feedback-mastery',
    name: 'Feedback Mastery',
    trigger: '"give feedback"',
    description: 'Deliver constructive feedback using Situation-Behavior-Impact (SBI) technique.',
    bundle: 'tools-utilities',
    tier: 'standard',
    grimoire_ready: false,
    source: 'openclaw',
    status: 'active',
    keywords: ['feedback', 'communication', 'sbi'],
  },
  {
    id: 'daily-meeting-update',
    name: 'Daily Meeting Update',
    trigger: '"daily" / "standup" / "scrum"',
    description: 'Interactive daily standup generator. Pulls activity from GitHub/git/Jira if available.',
    bundle: 'tools-utilities',
    tier: 'standard',
    grimoire_ready: false,
    source: 'openclaw',
    status: 'active',
    keywords: ['standup', 'daily', 'meeting', 'scrum'],
  },
  {
    id: 'professional-communication',
    name: 'Professional Comms',
    trigger: '"compose email" / "professional email"',
    description: 'Guide technical communication. Email structure, messaging etiquette, meeting agendas.',
    bundle: 'tools-utilities',
    tier: 'standard',
    grimoire_ready: false,
    source: 'openclaw',
    status: 'active',
    keywords: ['communication', 'email', 'meetings'],
  },
  // Commands
  {
    id: 'command-codex-plan',
    name: 'Codex Plan',
    trigger: '/codex-plan',
    description: 'Create a detailed implementation plan using Codex 5.2 with high reasoning.',
    bundle: 'tools-utilities',
    tier: 'standard',
    grimoire_ready: false,
    source: 'openclaw',
    status: 'active',
    keywords: ['planning', 'codex', 'implementation'],
  },
  {
    id: 'command-compose-email',
    name: 'Compose Email',
    trigger: '/compose-email',
    description: 'Draft a professional email using the What-Why-How framework.',
    bundle: 'tools-utilities',
    tier: 'standard',
    grimoire_ready: false,
    source: 'openclaw',
    status: 'active',
    keywords: ['email', 'communication', 'professional'],
  },
  {
    id: 'command-explain-changes-mental-model',
    name: 'Explain Changes',
    trigger: '/explain-changes-mental-model',
    description: 'Build a mental model of changes by splitting them into smaller logical chunks.',
    bundle: 'tools-utilities',
    tier: 'standard',
    grimoire_ready: false,
    source: 'openclaw',
    status: 'active',
    keywords: ['code-review', 'understanding', 'mental-model'],
  },
  {
    id: 'command-explain-pr-changes',
    name: 'Explain PR Changes',
    trigger: '/explain-pr-changes',
    description: 'Generate comprehensive markdown summary of pull request changes with visual impact analysis.',
    bundle: 'tools-utilities',
    tier: 'standard',
    grimoire_ready: false,
    source: 'openclaw',
    status: 'active',
    keywords: ['git', 'pull-requests', 'documentation'],
  },
  {
    id: 'command-sync-branch',
    name: 'Sync Branch',
    trigger: '/sync-branch',
    description: 'Sync feature branch with the latest main branch.',
    bundle: 'tools-utilities',
    tier: 'standard',
    grimoire_ready: false,
    source: 'openclaw',
    status: 'active',
    keywords: ['git', 'branches', 'sync'],
  },
  {
    id: 'command-sync-skills-readme',
    name: 'Sync Skills README',
    trigger: '/sync-skills-readme',
    description: 'Sync root README.md with current skills inventory from skills/ directory.',
    bundle: 'tools-utilities',
    tier: 'standard',
    grimoire_ready: false,
    source: 'openclaw',
    status: 'active',
    keywords: ['readme', 'sync', 'documentation'],
  },
  {
    id: 'command-viral-tweet',
    name: 'Viral Tweet',
    trigger: '/viral-tweet',
    description: 'Transform a raw tweet idea into an optimized viral post for X. 3 versions with posting strategy.',
    bundle: 'tools-utilities',
    tier: 'standard',
    grimoire_ready: false,
    source: 'openclaw',
    status: 'active',
    keywords: ['social-media', 'twitter', 'x', 'viral'],
  },
  {
    id: 'command-cancel-review',
    name: 'Cancel Review',
    trigger: '/cancel-review',
    description: 'Cancel an active review loop.',
    bundle: 'tools-utilities',
    tier: 'standard',
    grimoire_ready: false,
    source: 'claude-plugin',
    status: 'active',
    keywords: ['review', 'cancel'],
  },
  // QA & Testing
  {
    id: 'qa-test-planner',
    name: 'QA Test Planner',
    trigger: '"create test plan"',
    description: 'Generate comprehensive test plans, manual test cases, regression test suites, and bug reports.',
    bundle: 'tools-utilities',
    tier: 'standard',
    grimoire_ready: false,
    source: 'openclaw',
    status: 'active',
    keywords: ['testing', 'qa', 'test-plans', 'regression'],
  },
  {
    id: 'datadog-cli',
    name: 'Datadog CLI',
    trigger: '"datadog" / "search logs"',
    description: 'Search logs, query metrics, trace requests, and manage Datadog dashboards.',
    bundle: 'tools-utilities',
    tier: 'standard',
    grimoire_ready: false,
    source: 'openclaw',
    status: 'active',
    keywords: ['datadog', 'logging', 'metrics', 'observability'],
  },

  // ═══════════════════════════════════════════
  //  NOISE TIER (hidden by default)
  // ═══════════════════════════════════════════
  {
    id: 'ethical-hacking-methodology',
    name: 'Ethical Hacking',
    trigger: '/ethical-hacking-methodology',
    description: 'Archived — replaced by bounty-hunting. Systematic methodology for penetration testing.',
    bundle: 'security-web3',
    tier: 'noise',
    grimoire_ready: false,
    source: 'antigravity',
    status: 'active',
    keywords: ['security', 'hacking', 'pentesting', 'archived'],
  },
  {
    id: 'api-fuzzing-bug-bounty',
    name: 'API Fuzzing (Bug Bounty)',
    trigger: '/api-fuzzing-bug-bounty',
    description: 'Archived — replaced by bounty-hunting. API fuzzing techniques for bug bounty programs.',
    bundle: 'security-web3',
    tier: 'noise',
    grimoire_ready: false,
    source: 'antigravity',
    status: 'active',
    keywords: ['security', 'api', 'fuzzing', 'archived'],
  },
  {
    id: 'plugin-forge',
    name: 'Plugin Forge',
    trigger: '"create plugin"',
    description: 'Internal — Create and manage Claude Code plugins with proper structure and manifests.',
    bundle: 'ai-agents',
    tier: 'noise',
    grimoire_ready: false,
    source: 'openclaw',
    status: 'active',
    keywords: ['meta', 'plugins', 'internal'],
  },
  {
    id: 'agent-md-refactor',
    name: 'Agent MD Refactor',
    trigger: '"refactor agents.md"',
    description: 'Internal — Refactor bloated AGENTS.md or CLAUDE.md files using progressive disclosure.',
    bundle: 'ai-agents',
    tier: 'noise',
    grimoire_ready: false,
    source: 'openclaw',
    status: 'active',
    keywords: ['meta', 'refactor', 'internal'],
  },
  {
    id: 'command-creator',
    name: 'Command Creator',
    trigger: '"create a command"',
    description: 'Internal — Create Claude Code slash commands. Document workflows as reusable commands.',
    bundle: 'ai-agents',
    tier: 'noise',
    grimoire_ready: false,
    source: 'openclaw',
    status: 'active',
    keywords: ['meta', 'commands', 'internal'],
  },
  {
    id: 'skill-judge',
    name: 'Skill Judge',
    trigger: '"evaluate skill"',
    description: 'Internal — Evaluate Agent Skill design quality against official specifications.',
    bundle: 'ai-agents',
    tier: 'noise',
    grimoire_ready: false,
    source: 'openclaw',
    status: 'active',
    keywords: ['meta', 'skills', 'quality', 'internal'],
  },
  {
    id: 'session-handoff',
    name: 'Session Handoff',
    trigger: '"create handoff" / "session ending"',
    description: 'Internal — Creates comprehensive handoff documents for seamless AI agent session transfers.',
    bundle: 'tools-utilities',
    tier: 'noise',
    grimoire_ready: false,
    source: 'openclaw',
    status: 'active',
    keywords: ['handoff', 'context', 'session', 'internal'],
  },
  {
    id: 'lesson-learned',
    name: 'Lesson Learned',
    trigger: '"what\'s the lesson"',
    description: 'Internal — Analyze recent code changes via git history and extract software engineering lessons.',
    bundle: 'tools-utilities',
    tier: 'noise',
    grimoire_ready: false,
    source: 'openclaw',
    status: 'active',
    keywords: ['reflection', 'git', 'learning', 'internal'],
  },
  {
    id: 'dependency-updater',
    name: 'Dependency Updater',
    trigger: '"update dependencies"',
    description: 'Internal — Smart dependency management. Auto-detects project type, applies safe updates.',
    bundle: 'tools-utilities',
    tier: 'noise',
    grimoire_ready: false,
    source: 'openclaw',
    status: 'active',
    keywords: ['dependencies', 'updates', 'internal'],
  },
];
