// ========== AGENT GRIMOIRE DATA ==========
// Bundle + Tier system for Agent Grimoire marketplace
// Last updated: 2026-02-24

window.BUNDLES = {
  'all':              { label: 'All' },
  'security-web3':    { label: 'Security & Web3' },
  'development':      { label: 'Dev' },
  'design-creative':  { label: 'Design & Creative' },
  'marketing-growth': { label: 'Marketing' },
  'cro-product':      { label: 'CRO & Product' },
  'ai-agents':        { label: 'AI & Agents' },
  'tools-utilities':  { label: 'Tools' },
};

window.TIERS = {
  legendary: { label: 'Legendary', color: '#FFD700', order: 0 },
  advanced:  { label: 'Advanced',  color: '#a855f7', order: 1 },
  standard:  { label: 'Standard',  color: '#3b82f6', order: 2 },
  noise:     { label: 'Noise',     color: '#444444', order: 3 },
};

window.SKILLS = [
  // ═══════════════════════════════════════════
  //  LEGENDARY TIER
  // ═══════════════════════════════════════════
  {
    id: 'simplicity-auditor',
    name: 'Simplicity Auditor',
    trigger: 'simplicity-auditor',
    description: 'Radical Simplicity & Candor Auditor. Audits products, systems, architecture, strategy, UX, and messaging for overengineering, ego-driven complexity, and premature abstraction. Returns structured YES/NO/DEFER decisions. Steve Jobs simplicity standards.',
    bundle: 'cro-product',
    tier: 'legendary',
    grimoire_ready: true,
    source: 'aria-custom',
    status: 'active',
    keywords: ['simplicity', 'audit', 'overengineering', 'product', 'architecture', 'complexity', 'candor', 'subtraction', 'steve jobs', 'decisions'],
  },
  {
    id: 'vibecoding',
    name: 'Vibecoding',
    trigger: 'vibecoding',
    description: 'Master vibecoding methodology. Research → Plan → Build → Test workflow with parallel agents.',
    bundle: 'development',
    tier: 'legendary',
    grimoire_ready: true,
    source: 'claude-skill',
    status: 'active',
    keywords: ['coding', 'workflow', 'session', 'planning', 'worktree'],
  },
  {
    id: 'bounty-hunting',
    name: 'Bounty Hunting',
    trigger: 'bounty-hunting',
    description: 'Smart contract security audit methodology for bug bounties on Cantina, Immunefi, Code4rena. Pre-submission checklist, PoC templates, report writing.',
    bundle: 'security-web3',
    tier: 'legendary',
    grimoire_ready: true,
    source: 'claude-skill',
    status: 'active',
    keywords: ['bounty', 'security', 'audit', 'smart contract', 'cantina', 'immunefi', 'code4rena'],
  },
  {
    id: 'crypto-merch-art',
    name: 'Crypto Merch Art',
    trigger: '/crypto-merch-art',
    description: 'Contest-specific art direction for RedotPay x Superteam Brasil. Archived — too narrow for general use. Kept internally.',
    bundle: 'design-creative',
    tier: 'standard',
    grimoire_ready: false,
    source: 'aria-custom',
    status: 'archived',
    keywords: ['merch', 'illustration', 'streetwear', 'crypto art', 'midjourney', 'character design', 'superteam'],
  },
  {
    id: 'merch-production',
    name: 'Merch Production by Marco',
    trigger: '/merch-production',
    description: 'Marco is a senior designer who takes AI-generated PNGs to print-ready production files. Rohit 3-level system: quick start → full 9-step workflow → reference library. Vectorization, AI text replacement, human-touch post-processing, color reduction, scale testing, export. The skill that bridges "cool AI image" and "real thing you can wear." v2.0 with full Rohit architecture.',
    bundle: 'design-creative',
    tier: 'advanced',
    grimoire_ready: true,
    source: 'aria-custom',
    status: 'active',
    keywords: ['merch', 'vector', 'figma', 'production', 'screen print', 'print-ready', 'marco', 'human-touch', 'font replacement'],
  },
  {
    id: 'blog-post-writer',
    name: 'Blog Post Writer',
    trigger: '/blog-post-writer',
    description: 'Universal blog post pipeline for writers, PMs, and founders. Six stages: Aria interviews you about the topic → researches social pulse + articles → writes a brain dump draft in your natural voice → captures your voice reaction (WisprFlow/Whisper/text) → clones your brand voice from past articles → humanizer pass. Works for any company, any topic, any writer. First-time-user ready. v2.0 Legendary.',
    bundle: 'marketing-growth',
    tier: 'legendary',
    grimoire_ready: true,
    source: 'aria-custom',
    status: 'active',
    keywords: ['blog post', 'writing', 'voice clone', 'wisprflow', 'humanizer', 'publication', 'style steal', 'interview', 'content'],
  },
  {
    id: 'blog-post-voice-pipeline',
    name: 'Blog Post Voice Pipeline',
    trigger: '/voice-pipeline-start',
    description: 'The Aria x Gabe method. Record in your native language (PT, FR, ES, EN) via WisprFlow directly in Obsidian. Aria acts as podcast host — provides interview questions + cheat sheet so you never need full technical depth. Near-literal translation preserves your natural speech patterns, not polished prose. Voice fingerprint applied. 24-pattern humanizer pass. Co-marketing legal workaround for regulated claims. Proven on Octant x Yearn Finance (Feb 2026). Better than /voicenotetoletter on every dimension. v1.0 Legendary.',
    bundle: 'marketing-growth',
    tier: 'advanced',
    grimoire_ready: false,
    source: 'aria-custom',
    status: 'archived',
    keywords: ['blog post', 'voice note', 'wisprflow', 'obsidian', 'native language', 'bilingual', 'interview format', 'near-literal translation', 'humanizer', 'voice clone', 'co-marketing'],
  },
  {
    id: 'senior-dev-review',
    name: 'Senior Dev Review (Marcus Mode)',
    trigger: '/senior-dev-review',
    description: 'Reviews AI-generated or vibe-coded code as a senior production engineer would. Not "does it work?" but "what happens when things goes wrong?" Eight review categories: circuit breakers, error differentiation, retry behavior, observability, graceful degradation, happy path gaps, load/race conditions, security assumptions. Output includes a 3 AM scenario and production-ready score. Based on a real $12,400 AWS incident. v1.0 Legendary.',
    bundle: 'development',
    tier: 'legendary',
    grimoire_ready: true,
    source: 'aria-custom',
    status: 'active',
    keywords: ['code review', 'production', 'reliability', 'circuit breaker', 'senior dev', 'marcus', 'ai code', 'vibe coding', 'incident'],
  },
  {
    id: 'obsidian-agent-os',
    name: 'Obsidian Agent OS',
    trigger: '/obsidian-agent-os',
    description: 'Build a 24/7 personal OS in Obsidian wired to AI agents. Three modes: SETUP (vault architecture for agent synergy), COMPRESS (NotebookLM + YouTube extension + Book Filter pipeline for 10x faster learning), VOICE (extract any publication\'s writing style and apply it to your draft). Includes 7 slash commands (/context, /trace, /ghost, /connect, /ideas, /graduate, /emerge), WisprFlow brain dump workflow, full humanizer pass, and vault health validator. v1.0 — Legendary. Sources: Greg Isenberg, polydao, Rohit, internetVin, AtlasForgeAI.',
    bundle: 'ai-agents',
    tier: 'legendary',
    grimoire_ready: true,
    source: 'aria-custom',
    status: 'active',
    keywords: ['obsidian', 'notebooklm', 'second brain', 'personal os', 'knowledge management', 'writing voice', 'wisprflow', 'slash commands', 'learning', 'blog post'],
  },
  {
    id: 'humanizer',
    name: 'Humanizer',
    trigger: '"humanize text"',
    description: 'Strip AI writing patterns from text. Make prose sound natural and human-written. Run on any user-facing content before sending.',
    bundle: 'design-creative',
    tier: 'advanced',
    grimoire_ready: true,
    source: 'openclaw',
    status: 'active',
    keywords: ['writing', 'ai-detection', 'editing', 'prose', 'natural'],
  },

  // ═══════════════════════════════════════════
  //  ADVANCED TIER
  // ═══════════════════════════════════════════
  {
    id: 'dev-solidity',
    name: 'Solidity Dev',
    trigger: 'dev-solidity',
    description: 'EVM development with Solidity, Foundry, and security patterns. For Ethereum, Base, and L2 builds.',
    bundle: 'security-web3',
    tier: 'advanced',
    grimoire_ready: true,
    source: 'claude-skill',
    status: 'active',
    keywords: ['solidity', 'evm', 'ethereum', 'foundry', 'smart contract', 'defi', 'base'],
  },
  {
    id: 'dev-solana',
    name: 'Solana Dev',
    trigger: 'dev-solana',
    description: 'Solana development with Anchor, Pinocchio, and security patterns. For hackathons and audits.',
    bundle: 'security-web3',
    tier: 'advanced',
    grimoire_ready: true,
    source: 'claude-skill',
    status: 'active',
    keywords: ['solana', 'anchor', 'rust', 'pinocchio', 'spl', 'token-2022', 'hackathon'],
  },
  {
    id: 'solidity-security',
    name: 'Solidity Security',
    trigger: '/solidity-security',
    description: 'Smart contract security patterns for Solidity. Reentrancy, overflow, access control, and EVM-specific vulnerabilities.',
    bundle: 'security-web3',
    tier: 'advanced',
    grimoire_ready: true,
    source: 'antigravity',
    status: 'active',
    keywords: ['security', 'solidity', 'smart-contracts', 'evm', 'defi'],
  },
  {
    id: 'vulnerability-scanner',
    name: 'Vulnerability Scanner',
    trigger: '/vulnerability-scanner',
    description: 'Advanced vulnerability analysis and scanning patterns for identifying security weaknesses.',
    bundle: 'security-web3',
    tier: 'advanced',
    grimoire_ready: true,
    source: 'antigravity',
    status: 'active',
    keywords: ['security', 'vulnerability', 'scanning', 'analysis'],
  },
  {
    id: 'media-gen',
    name: 'Media Gen',
    trigger: 'media-gen',
    description: 'AI image and video generation with Nano Banana (Gemini), Veo 3, Midjourney, and more.',
    bundle: 'design-creative',
    tier: 'advanced',
    grimoire_ready: true,
    source: 'claude-skill',
    status: 'active',
    keywords: ['image', 'video', 'generation', 'midjourney', 'gemini', 'veo', 'ai art'],
  },
  {
    id: 'ui-ux-pro-max',
    name: 'UI/UX Pro Max',
    trigger: '/ui-ux-pro-max',
    description: 'Premium design systems and tokens. Advanced patterns for beautiful, accessible, production-ready UIs.',
    bundle: 'development',
    tier: 'advanced',
    grimoire_ready: true,
    source: 'antigravity',
    status: 'active',
    keywords: ['design', 'ui', 'ux', 'design-system', 'tokens', 'accessibility'],
  },
  {
    id: 'advisory-council',
    name: 'Advisory Council',
    trigger: 'advisory-council',
    description: 'Multi-persona analysis system. Get parallel perspectives from independent AI experts on any problem.',
    bundle: 'ai-agents',
    tier: 'legendary',
    grimoire_ready: true,
    source: 'claude-skill',
    status: 'active',
    keywords: ['multi-persona', 'analysis', 'perspectives', 'experts', 'council'],
  },
  {
    id: 'marketing',
    name: 'Marketing',
    trigger: 'marketing',
    description: 'GTM strategy, copywriting, content creation with recursive self-improvement loops.',
    bundle: 'marketing-growth',
    tier: 'advanced',
    grimoire_ready: true,
    source: 'claude-skill',
    status: 'active',
    keywords: ['gtm', 'strategy', 'copywriting', 'content', 'growth'],
  },
  {
    id: 'product-manager-toolkit',
    name: 'PM Toolkit',
    trigger: '/product-manager-toolkit',
    description: 'RICE prioritization, PRD templates, roadmap planning, and product strategy frameworks for PMs.',
    bundle: 'cro-product',
    tier: 'advanced',
    grimoire_ready: true,
    source: 'antigravity',
    status: 'active',
    keywords: ['product', 'pm', 'rice', 'prd', 'roadmap', 'prioritization'],
  },
  {
    id: 'nextjs-best-practices',
    name: 'Next.js Best Practices',
    trigger: '/nextjs-best-practices',
    description: 'Next.js 15+ App Router patterns. Server components, caching, streaming, and performance optimization.',
    bundle: 'development',
    tier: 'advanced',
    grimoire_ready: false,
    source: 'antigravity',
    status: 'active',
    keywords: ['nextjs', 'react', 'app-router', 'frontend', 'performance'],
  },
  {
    id: 'systematic-debugging',
    name: 'Systematic Debugging',
    trigger: '/systematic-debugging',
    description: 'Debug like a pro. Structured approach to isolating, reproducing, and fixing bugs systematically.',
    bundle: 'development',
    tier: 'advanced',
    grimoire_ready: false,
    source: 'antigravity',
    status: 'active',
    keywords: ['debugging', 'errors', 'troubleshooting', 'systematic'],
  },

  // ═══════════════════════════════════════════
  //  STANDARD TIER — Security & Web3
  // ═══════════════════════════════════════════
  {
    id: 'security-review',
    name: 'Security Review',
    trigger: 'security-review',
    description: 'Comprehensive security checklist for auth, user input, secrets, API endpoints, and payment features.',
    bundle: 'security-web3',
    tier: 'standard',
    grimoire_ready: false,
    source: 'ecc',
    status: 'active',
    keywords: ['security', 'auth', 'owasp', 'checklist', 'review', 'vulnerabilities'],
  },
  {
    id: 'defi-protocol-templates',
    name: 'DeFi Protocol Templates',
    trigger: '/defi-protocol-templates',
    description: 'DeFi protocol implementation templates. AMMs, lending, staking, yield farming, and governance patterns.',
    bundle: 'security-web3',
    tier: 'standard',
    grimoire_ready: false,
    source: 'antigravity',
    status: 'active',
    keywords: ['defi', 'amm', 'lending', 'staking', 'yield', 'governance', 'solidity'],
  },

  // ═══════════════════════════════════════════
  //  STANDARD TIER — Development
  // ═══════════════════════════════════════════
  {
    id: 'frontend-patterns',
    name: 'Frontend Patterns',
    trigger: 'frontend-patterns',
    description: 'React and Next.js patterns, state management, performance optimization, and UI best practices.',
    bundle: 'development',
    tier: 'standard',
    grimoire_ready: false,
    source: 'ecc',
    status: 'active',
    keywords: ['react', 'nextjs', 'frontend', 'ui', 'state', 'performance', 'patterns'],
  },
  {
    id: 'backend-patterns',
    name: 'Backend Patterns',
    trigger: 'backend-patterns',
    description: 'API design, database optimization, and server-side patterns for Node.js, Express, and Next.js API routes.',
    bundle: 'development',
    tier: 'standard',
    grimoire_ready: false,
    source: 'ecc',
    status: 'active',
    keywords: ['api', 'backend', 'nodejs', 'express', 'nextjs', 'server', 'patterns'],
  },
  {
    id: 'postgres-patterns',
    name: 'Postgres Patterns',
    trigger: 'postgres-patterns',
    description: 'PostgreSQL query optimization, schema design, indexing, and security. Based on Supabase best practices.',
    bundle: 'development',
    tier: 'standard',
    grimoire_ready: false,
    source: 'ecc',
    status: 'active',
    keywords: ['postgres', 'postgresql', 'supabase', 'database', 'sql', 'query', 'indexing'],
  },
  {
    id: 'supabase-automation',
    name: 'Supabase Automation',
    trigger: '/supabase-automation',
    description: 'Automate Supabase workflows. Schema migrations, RLS policies, Edge Functions, and storage management.',
    bundle: 'development',
    tier: 'standard',
    grimoire_ready: false,
    source: 'antigravity',
    status: 'active',
    keywords: ['supabase', 'postgres', 'database', 'rls', 'automation'],
  },

  // ═══════════════════════════════════════════
  //  STANDARD TIER — Design & Creative
  // ═══════════════════════════════════════════,
  {
    id: 'video-pipeline',
    name: 'Video Pipeline',
    trigger: 'video-pipeline',
    description: 'Video creation pipeline with Remotion, HeyGen, demo recording, and automation.',
    bundle: 'design-creative',
    tier: 'advanced',
    grimoire_ready: false,
    source: 'claude-skill',
    status: 'active',
    keywords: ['video', 'remotion', 'heygen', 'recording', 'automation'],
  },

  // ═══════════════════════════════════════════
  //  STANDARD TIER — Marketing & Growth
  // ═══════════════════════════════════════════
  {
    id: 'content-strategy',
    name: 'Content Strategy',
    trigger: 'content-strategy',
    description: 'Plan content strategy, decide what to create, and figure out topics to cover for growth.',
    bundle: 'marketing-growth',
    tier: 'standard',
    grimoire_ready: false,
    source: 'claude-skill',
    status: 'active',
    keywords: ['content', 'strategy', 'topics', 'planning', 'growth'],
  },
  {
    id: 'social-content',
    name: 'Social Content',
    trigger: 'social-content',
    description: 'Create, schedule, and optimize social media content for LinkedIn, Twitter/X, Instagram, and TikTok.',
    bundle: 'marketing-growth',
    tier: 'standard',
    grimoire_ready: false,
    source: 'claude-skill',
    status: 'active',
    keywords: ['social media', 'linkedin', 'twitter', 'instagram', 'tiktok'],
  },
  {
    id: 'copywriting',
    name: 'Copywriting',
    trigger: 'copywriting',
    description: 'Write, rewrite, or improve marketing copy for homepages, landing pages, pricing pages, and product pages.',
    bundle: 'marketing-growth',
    tier: 'standard',
    grimoire_ready: false,
    source: 'claude-skill',
    status: 'active',
    keywords: ['copy', 'writing', 'landing page', 'marketing', 'conversion'],
  },
  {
    id: 'email-sequence',
    name: 'Email Sequence',
    trigger: 'email-sequence',
    description: 'Create or optimize email sequences, drip campaigns, automated flows, and lifecycle emails.',
    bundle: 'marketing-growth',
    tier: 'standard',
    grimoire_ready: false,
    source: 'claude-skill',
    status: 'active',
    keywords: ['email', 'drip', 'nurture', 'sequence', 'automation'],
  },
  {
    id: 'paid-ads',
    name: 'Paid Ads',
    trigger: 'paid-ads',
    description: 'Paid advertising campaigns on Google Ads, Meta, LinkedIn, and Twitter/X. Ad copy, targeting, and optimization.',
    bundle: 'marketing-growth',
    tier: 'standard',
    grimoire_ready: false,
    source: 'claude-skill',
    status: 'active',
    keywords: ['ppc', 'ads', 'google', 'meta', 'linkedin', 'paid media'],
  },
  {
    id: 'programmatic-seo',
    name: 'Programmatic SEO',
    trigger: 'programmatic-seo',
    description: 'Create SEO-driven pages at scale using templates and data. Directory, location, and keyword pages.',
    bundle: 'marketing-growth',
    tier: 'standard',
    grimoire_ready: false,
    source: 'claude-skill',
    status: 'active',
    keywords: ['seo', 'programmatic', 'templates', 'directory', 'scale'],
  },
  {
    id: 'launch-strategy',
    name: 'Launch Strategy',
    trigger: 'launch-strategy',
    description: 'Plan product launches, feature announcements, and release strategies including Product Hunt.',
    bundle: 'marketing-growth',
    tier: 'standard',
    grimoire_ready: false,
    source: 'claude-skill',
    status: 'active',
    keywords: ['launch', 'product hunt', 'release', 'announcement', 'go-to-market'],
  },
  {
    id: 'free-tool-strategy',
    name: 'Free Tool Strategy',
    trigger: 'free-tool-strategy',
    description: 'Plan and build free tools for marketing — lead generation, SEO value, and brand awareness.',
    bundle: 'marketing-growth',
    tier: 'standard',
    grimoire_ready: false,
    source: 'claude-skill',
    status: 'active',
    keywords: ['free tool', 'engineering as marketing', 'lead gen', 'seo'],
  },
  {
    id: 'pricing-strategy',
    name: 'Pricing Strategy',
    trigger: 'pricing-strategy',
    description: 'Pricing decisions, packaging, monetization strategy. Freemium, trials, tiers, and value metrics.',
    bundle: 'marketing-growth',
    tier: 'standard',
    grimoire_ready: false,
    source: 'claude-skill',
    status: 'active',
    keywords: ['pricing', 'freemium', 'tiers', 'monetization', 'packaging'],
  },
  {
    id: 'referral-program',
    name: 'Referral Program',
    trigger: 'referral-program',
    description: 'Create and optimize referral programs, affiliate programs, and word-of-mouth strategies.',
    bundle: 'marketing-growth',
    tier: 'standard',
    grimoire_ready: false,
    source: 'claude-skill',
    status: 'active',
    keywords: ['referral', 'affiliate', 'word of mouth', 'viral', 'ambassador'],
  },
  {
    id: 'market-sizing-analysis',
    name: 'Market Sizing',
    trigger: '/market-sizing-analysis',
    description: 'TAM/SAM/SOM calculations and market sizing methodology for pitches and strategic planning.',
    bundle: 'marketing-growth',
    tier: 'standard',
    grimoire_ready: false,
    source: 'antigravity',
    status: 'active',
    keywords: ['market', 'tam', 'sam', 'som', 'sizing', 'analysis'],
  },
  {
    id: 'marketing-ideas',
    name: 'Marketing Ideas',
    trigger: 'marketing-ideas',
    description: 'Marketing ideas, inspiration, and strategies for SaaS and software products.',
    bundle: 'marketing-growth',
    tier: 'standard',
    grimoire_ready: false,
    source: 'claude-skill',
    status: 'active',
    keywords: ['marketing', 'ideas', 'growth', 'strategies', 'inspiration'],
  },
  {
    id: 'marketing-psychology',
    name: 'Marketing Psychology',
    trigger: 'marketing-psychology',
    description: 'Apply psychological principles, mental models, and behavioral science to marketing.',
    bundle: 'marketing-growth',
    tier: 'advanced',
    grimoire_ready: false,
    source: 'claude-skill',
    status: 'active',
    keywords: ['psychology', 'mental models', 'cognitive bias', 'persuasion', 'behavior'],
  },
  {
    id: 'competitor-alternatives',
    name: 'Competitor Alternatives',
    trigger: 'competitor-alternatives',
    description: 'Create competitor comparison and alternative pages for SEO and sales enablement.',
    bundle: 'marketing-growth',
    tier: 'standard',
    grimoire_ready: false,
    source: 'claude-skill',
    status: 'active',
    keywords: ['competitor', 'alternatives', 'comparison', 'vs page', 'seo'],
  },

  // ═══════════════════════════════════════════
  //  STANDARD TIER — CRO & Product
  // ═══════════════════════════════════════════
  {
    id: 'form-cro',
    name: 'Form CRO',
    trigger: 'form-cro',
    description: 'Optimize lead capture, contact, demo request, application, and checkout forms for conversion.',
    bundle: 'cro-product',
    tier: 'standard',
    grimoire_ready: false,
    source: 'claude-skill',
    status: 'active',
    keywords: ['form', 'cro', 'conversion', 'lead capture', 'optimization'],
  },
  {
    id: 'page-cro',
    name: 'Page CRO',
    trigger: 'page-cro',
    description: 'Optimize any marketing page for conversions — homepage, landing pages, pricing, feature pages.',
    bundle: 'cro-product',
    tier: 'standard',
    grimoire_ready: false,
    source: 'claude-skill',
    status: 'active',
    keywords: ['page', 'cro', 'conversion', 'landing page', 'optimization'],
  },
  {
    id: 'signup-flow-cro',
    name: 'Signup Flow CRO',
    trigger: 'signup-flow-cro',
    description: 'Optimize signup, registration, account creation, and trial activation flows.',
    bundle: 'cro-product',
    tier: 'standard',
    grimoire_ready: false,
    source: 'claude-skill',
    status: 'active',
    keywords: ['signup', 'registration', 'trial', 'activation', 'cro'],
  },
  {
    id: 'onboarding-cro',
    name: 'Onboarding CRO',
    trigger: 'onboarding-cro',
    description: 'Optimize post-signup onboarding, user activation, first-run experience, and time-to-value.',
    bundle: 'cro-product',
    tier: 'standard',
    grimoire_ready: false,
    source: 'claude-skill',
    status: 'active',
    keywords: ['onboarding', 'activation', 'first-run', 'time-to-value', 'cro'],
  },
  {
    id: 'paywall-upgrade-cro',
    name: 'Paywall Upgrade CRO',
    trigger: 'paywall-upgrade-cro',
    description: 'Create or optimize in-app paywalls, upgrade screens, upsell modals, and feature gates.',
    bundle: 'cro-product',
    tier: 'standard',
    grimoire_ready: false,
    source: 'claude-skill',
    status: 'active',
    keywords: ['paywall', 'upgrade', 'upsell', 'feature gate', 'cro'],
  },
  {
    id: 'popup-cro',
    name: 'Popup CRO',
    trigger: 'popup-cro',
    description: 'Create or optimize popups, modals, overlays, slide-ins, and banners for conversion.',
    bundle: 'cro-product',
    tier: 'standard',
    grimoire_ready: false,
    source: 'claude-skill',
    status: 'active',
    keywords: ['popup', 'modal', 'exit intent', 'overlay', 'cro'],
  },
  {
    id: 'ab-test-setup',
    name: 'A/B Test Setup',
    trigger: 'ab-test-setup',
    description: 'Plan, design, and implement A/B tests and experiments with variant copy and analysis.',
    bundle: 'cro-product',
    tier: 'standard',
    grimoire_ready: false,
    source: 'claude-skill',
    status: 'active',
    keywords: ['ab test', 'split test', 'experiment', 'variant', 'cro'],
  },
  {
    id: 'analytics-tracking',
    name: 'Analytics Tracking',
    trigger: 'analytics-tracking',
    description: 'Set up and audit analytics tracking — GA4, conversion tracking, event tracking, UTM parameters.',
    bundle: 'cro-product',
    tier: 'standard',
    grimoire_ready: false,
    source: 'claude-skill',
    status: 'active',
    keywords: ['analytics', 'ga4', 'tracking', 'conversion', 'utm'],
  },
  {
    id: 'schema-markup',
    name: 'Schema Markup',
    trigger: 'schema-markup',
    description: 'Add, fix, or optimize schema markup and structured data. JSON-LD, rich snippets, FAQ schema.',
    bundle: 'cro-product',
    tier: 'standard',
    grimoire_ready: false,
    source: 'claude-skill',
    status: 'active',
    keywords: ['schema', 'structured data', 'json-ld', 'rich snippets', 'seo'],
  },
  {
    id: 'product-marketing-context',
    name: 'Product Marketing Context',
    trigger: 'product-marketing-context',
    description: 'Create or update product marketing context documents — positioning, messaging, and audience.',
    bundle: 'cro-product',
    tier: 'standard',
    grimoire_ready: false,
    source: 'claude-skill',
    status: 'active',
    keywords: ['product', 'marketing', 'context', 'positioning', 'messaging'],
  },

  // ═══════════════════════════════════════════
  //  STANDARD TIER — AI & Agents
  // ═══════════════════════════════════════════
  {
    id: 'mcp-builder',
    name: 'MCP Builder',
    trigger: '/mcp-builder',
    description: 'Create your own MCP tools. Build, test, and publish Model Context Protocol servers for Claude.',
    bundle: 'ai-agents',
    tier: 'advanced',
    grimoire_ready: false,
    source: 'antigravity',
    status: 'active',
    keywords: ['mcp', 'tools', 'claude', 'protocol', 'agents', 'builder'],
  },
  {
    id: 'brainstorming',
    name: 'Brainstorming',
    trigger: '/brainstorming',
    description: 'Multi-perspective brainstorming for ideas, MVPs, and creative problem solving.',
    bundle: 'ai-agents',
    tier: 'standard',
    grimoire_ready: false,
    source: 'antigravity',
    status: 'active',
    keywords: ['brainstorming', 'ideas', 'mvp', 'creativity', 'planning'],
  },
  {
    id: 'continuous-learning-v2',
    name: 'Continuous Learning',
    trigger: 'continuous-learning-v2',
    description: 'Instinct-based learning that observes sessions, creates atomic instincts with confidence scoring, and evolves them into reusable skills.',
    bundle: 'ai-agents',
    tier: 'advanced',
    grimoire_ready: false,
    source: 'ecc',
    status: 'active',
    keywords: ['learning', 'instincts', 'patterns', 'evolve', 'skills', 'memory'],
  },
  {
    id: 'concise-planning',
    name: 'Concise Planning',
    trigger: '/concise-planning',
    description: 'Always start with a plan. Structured task breakdown before writing a single line of code.',
    bundle: 'ai-agents',
    tier: 'standard',
    grimoire_ready: false,
    source: 'antigravity',
    status: 'active',
    keywords: ['planning', 'breakdown', 'tasks', 'workflow', 'pre-coding'],
  },

  // ═══════════════════════════════════════════
  //  STANDARD TIER — Tools & Utilities
  // ═══════════════════════════════════════════
  {
    id: 'vercel-deployment',
    name: 'Vercel Deployment',
    trigger: '/vercel-deployment',
    description: 'Deploy to Vercel like a pro. Zero-config deployments, env vars, preview URLs, and custom domains.',
    bundle: 'tools-utilities',
    tier: 'standard',
    grimoire_ready: false,
    source: 'antigravity',
    status: 'active',
    keywords: ['vercel', 'deployment', 'hosting', 'frontend', 'serverless'],
  },
  // Documentation tools,
  // Professional tools,
  // Commands,
  // QA & Testing,

  // ═══════════════════════════════════════════
  //  NOISE TIER (hidden by default)
  // ═══════════════════════════════════════════,
  {
    id: 'voice-clone',
    name: 'Voice Clone',
    trigger: 'voice-clone',
    description: 'Clone any brand, protocol, or person\'s writing voice for blog posts, announcements, and co-marketing content. 4-phase process: Source Gathering → Pattern Extraction → Voice Capture → Apply & Verify. Produces a reusable voice-capture.md fingerprint. Includes Yearn Finance as a production example. Works on any source: X/Twitter, blogs, docs, interviews.',
    bundle: 'marketing-growth',
    tier: 'legendary',
    grimoire_ready: true,
    source: 'aria-custom',
    status: 'active',
    keywords: ['voice', 'clone', 'brand', 'tone', 'writing', 'blog', 'co-marketing', 'content', 'fingerprint', 'yearn', 'defi'],
  },
];
