// ========== SKILL DASHBOARD DATA ==========
// Source: marketplace.json + ~/.claude/skills/ + system skills
// Last updated: 2026-02-22

window.CATEGORIES = {
  'all':              { label: 'All',               color: 'green' },
  'ai-tools':         { label: 'AI Tools',          color: 'cyan' },
  'research':         { label: 'Research',          color: 'cyan' },
  'meta':             { label: 'Meta',              color: 'purple' },
  'documentation':    { label: 'Documentation',     color: 'amber' },
  'design-frontend':  { label: 'Design & Frontend', color: 'purple' },
  'development':      { label: 'Development',       color: 'green' },
  'code-review':      { label: 'Code Review',       color: 'green' },
  'planning':         { label: 'Planning',          color: 'amber' },
  'professional':     { label: 'Professional',      color: 'cyan' },
  'testing':          { label: 'Testing',           color: 'red' },
  'git':              { label: 'Git',               color: 'green' },
  'utilities':        { label: 'Utilities',         color: 'amber' },
  'agents':           { label: 'Agents',            color: 'purple' },
  'commands':         { label: 'Commands',          color: 'green' },
};

window.SKILLS = [
  // ── Claude Code Custom Skills ──
  {
    id: 'deep-research',
    name: 'Deep Research',
    trigger: '/deepsearch',
    description: 'Multi-step research with planning, decomposition, and long-context reasoning across tools and files.',
    category: 'research',
    source: 'claude-skill',
    status: 'active',
    keywords: ['research', 'search', 'analysis', 'deep dive', 'synthesis'],
  },
  {
    id: 'vibecoding',
    name: 'Vibecoding',
    trigger: 'vibecoding',
    description: 'Master vibecoding methodology. Research → Plan → Build → Test workflow with parallel agents.',
    category: 'development',
    source: 'claude-skill',
    status: 'active',
    keywords: ['coding', 'workflow', 'session', 'planning', 'worktree'],
  },

  // ── Claude Code Plugins ──
  {
    id: 'review-loop',
    name: 'Review Loop',
    trigger: '/review-loop',
    description: 'Implement task, get independent Codex review, address feedback in a structured loop.',
    category: 'code-review',
    source: 'claude-plugin',
    status: 'active',
    keywords: ['review', 'code review', 'feedback', 'codex'],
  },

  // ── AI Tools ──
  {
    id: 'codex',
    name: 'Codex (GPT-5.2)',
    trigger: '"codex exec" / "run codex"',
    description: 'Run Codex CLI for code analysis, refactoring, or automated editing. Uses GPT-5.2 for state-of-the-art software engineering.',
    category: 'ai-tools',
    source: 'openclaw',
    status: 'active',
    keywords: ['ai', 'code-analysis', 'gpt', 'codex', 'openai'],
  },
  {
    id: 'gemini',
    name: 'Gemini (Large Context)',
    trigger: '"run gemini" / "gemini review"',
    description: 'Run Gemini CLI for code review, plan review, or big context (>200k) processing. Uses Gemini 3 Pro.',
    category: 'ai-tools',
    source: 'openclaw',
    status: 'active',
    keywords: ['ai', 'code-review', 'large-context', 'gemini', 'google'],
  },
  {
    id: 'perplexity',
    name: 'Perplexity Search',
    trigger: '"search" / "look up" / "research"',
    description: 'Web search and research using Perplexity AI for generic queries and latest information.',
    category: 'ai-tools',
    source: 'openclaw',
    status: 'active',
    keywords: ['ai', 'search', 'research', 'perplexity', 'web'],
  },

  // ── Meta ──
  {
    id: 'agent-md-refactor',
    name: 'Agent MD Refactor',
    trigger: '"refactor agents.md"',
    description: 'Refactor bloated AGENTS.md, CLAUDE.md, or similar agent instruction files using progressive disclosure.',
    category: 'meta',
    source: 'openclaw',
    status: 'active',
    keywords: ['meta', 'refactor', 'claude-md', 'agents-md', 'documentation'],
  },
  {
    id: 'command-creator',
    name: 'Command Creator',
    trigger: '"create a command"',
    description: 'Create Claude Code slash commands. Document workflows as reusable commands.',
    category: 'meta',
    source: 'openclaw',
    status: 'active',
    keywords: ['meta', 'commands', 'slash-commands', 'claude-code'],
  },
  {
    id: 'plugin-forge',
    name: 'Plugin Forge',
    trigger: '"create plugin"',
    description: 'Create and manage Claude Code plugins with proper structure, manifests, and marketplace integration.',
    category: 'meta',
    source: 'openclaw',
    status: 'active',
    keywords: ['meta', 'plugins', 'marketplace', 'claude-code'],
  },
  {
    id: 'skill-judge',
    name: 'Skill Judge',
    trigger: '"evaluate skill"',
    description: 'Evaluate Agent Skill design quality against official specifications and best practices.',
    category: 'meta',
    source: 'openclaw',
    status: 'active',
    keywords: ['meta', 'skills', 'quality', 'review', 'audit'],
  },

  // ── Documentation ──
  {
    id: 'backend-to-frontend-handoff-docs',
    name: 'API Handoff Docs',
    trigger: '"create handoff docs"',
    description: 'Create API handoff documentation for frontend developers when backend work is complete.',
    category: 'documentation',
    source: 'openclaw',
    status: 'active',
    keywords: ['documentation', 'api', 'handoff', 'frontend', 'backend'],
  },
  {
    id: 'c4-architecture',
    name: 'C4 Architecture',
    trigger: '"architecture diagram" / "C4 diagram"',
    description: 'Generate architecture documentation using C4 model Mermaid diagrams.',
    category: 'documentation',
    source: 'openclaw',
    status: 'active',
    keywords: ['documentation', 'architecture', 'c4', 'mermaid', 'diagrams'],
  },
  {
    id: 'crafting-effective-readmes',
    name: 'Crafting READMEs',
    trigger: '"write readme" / "improve readme"',
    description: 'Templates and guidance for writing READMEs matched to your audience and project type.',
    category: 'documentation',
    source: 'openclaw',
    status: 'active',
    keywords: ['documentation', 'readme', 'writing', 'templates'],
  },
  {
    id: 'draw-io',
    name: 'Draw.io Diagrams',
    trigger: '"draw.io" / "create drawio"',
    description: 'Draw.io diagram creation, editing, and review. Supports .drawio XML editing and PNG conversion.',
    category: 'documentation',
    source: 'openclaw',
    status: 'active',
    keywords: ['documentation', 'diagrams', 'draw-io', 'xml'],
  },
  {
    id: 'excalidraw',
    name: 'Excalidraw',
    trigger: '"excalidraw"',
    description: 'Work with *.excalidraw files for diagrams, flowcharts, and architecture visualization.',
    category: 'documentation',
    source: 'openclaw',
    status: 'active',
    keywords: ['documentation', 'diagrams', 'excalidraw', 'visualization'],
  },
  {
    id: 'frontend-to-backend-requirements',
    name: 'FE-to-BE Requirements',
    trigger: '"document frontend needs"',
    description: 'Document frontend data needs for backend developers. Communicate API requirements clearly.',
    category: 'documentation',
    source: 'openclaw',
    status: 'active',
    keywords: ['documentation', 'api', 'requirements', 'frontend', 'backend'],
  },
  {
    id: 'marp-slide',
    name: 'Marp Slides',
    trigger: '"create slides" / "marp"',
    description: 'Create professional Marp presentation slides with 7 beautiful themes.',
    category: 'documentation',
    source: 'openclaw',
    status: 'active',
    keywords: ['documentation', 'presentations', 'slides', 'marp'],
  },
  {
    id: 'mermaid-diagrams',
    name: 'Mermaid Diagrams',
    trigger: '"create diagram" / "mermaid"',
    description: 'Comprehensive guide for creating software diagrams using Mermaid syntax.',
    category: 'documentation',
    source: 'openclaw',
    status: 'active',
    keywords: ['documentation', 'diagrams', 'mermaid', 'visualization', 'flowchart'],
  },
  {
    id: 'writing-clearly-and-concisely',
    name: 'Writing Clearly',
    trigger: '"write clearly" / "improve writing"',
    description: 'Write prose humans will read — documentation, commit messages, error messages, explanations, UI text.',
    category: 'documentation',
    source: 'openclaw',
    status: 'active',
    keywords: ['documentation', 'writing', 'communication', 'prose'],
  },

  // ── Design & Frontend ──
  {
    id: 'design-system-starter',
    name: 'Design System Starter',
    trigger: '"create design system"',
    description: 'Create and evolve design systems with design tokens, component architecture, and accessibility guidelines.',
    category: 'design-frontend',
    source: 'openclaw',
    status: 'active',
    keywords: ['design', 'frontend', 'design-system', 'tokens', 'accessibility'],
  },
  {
    id: 'mui',
    name: 'Material-UI v7',
    trigger: '"mui" / "material ui"',
    description: 'Material-UI v7 component library patterns including sx prop styling, theme integration, and responsive design.',
    category: 'design-frontend',
    source: 'openclaw',
    status: 'active',
    keywords: ['design', 'frontend', 'mui', 'material-ui', 'react'],
  },
  {
    id: 'openapi-to-typescript',
    name: 'OpenAPI to TypeScript',
    trigger: '"convert openapi"',
    description: 'Converts OpenAPI 3.0 JSON/YAML to TypeScript interfaces and type guards.',
    category: 'design-frontend',
    source: 'openclaw',
    status: 'active',
    keywords: ['design', 'frontend', 'openapi', 'typescript', 'api'],
  },
  {
    id: 'react-dev',
    name: 'React Dev',
    trigger: '"react component"',
    description: 'Build React components with TypeScript. Covers type-safe patterns for React 18-19.',
    category: 'design-frontend',
    source: 'openclaw',
    status: 'active',
    keywords: ['design', 'frontend', 'react', 'typescript', 'components'],
  },
  {
    id: 'react-useeffect',
    name: 'React useEffect',
    trigger: '"useEffect help"',
    description: 'React useEffect best practices from official docs. When NOT to use Effect and better alternatives.',
    category: 'design-frontend',
    source: 'openclaw',
    status: 'active',
    keywords: ['design', 'frontend', 'react', 'hooks', 'useeffect'],
  },

  // ── Development ──
  {
    id: 'database-schema-designer',
    name: 'Database Schema Designer',
    trigger: '"design schema" / "database design"',
    description: 'Design robust, scalable database schemas for SQL and NoSQL. Normalization, indexing, migration patterns.',
    category: 'development',
    source: 'openclaw',
    status: 'active',
    keywords: ['development', 'database', 'schema', 'sql', 'nosql'],
  },
  {
    id: 'dependency-updater',
    name: 'Dependency Updater',
    trigger: '"update dependencies"',
    description: 'Smart dependency management. Auto-detects project type, applies safe updates, prompts for major versions.',
    category: 'development',
    source: 'openclaw',
    status: 'active',
    keywords: ['development', 'dependencies', 'updates', 'npm', 'pip'],
  },
  {
    id: 'naming-analyzer',
    name: 'Naming Analyzer',
    trigger: '"suggest names" / "rename"',
    description: 'Suggest better variable, function, and class names based on context and conventions.',
    category: 'development',
    source: 'openclaw',
    status: 'active',
    keywords: ['development', 'naming', 'refactoring', 'code-quality'],
  },
  {
    id: 'reducing-entropy',
    name: 'Reducing Entropy',
    trigger: '"reduce entropy" / "minimize code"',
    description: 'Minimize total codebase size. Manual-only. Measures success by final code amount.',
    category: 'development',
    source: 'openclaw',
    status: 'active',
    keywords: ['development', 'refactoring', 'cleanup', 'code-size'],
  },
  {
    id: 'session-handoff',
    name: 'Session Handoff',
    trigger: '"create handoff" / "session ending"',
    description: 'Creates comprehensive handoff documents for seamless AI agent session transfers.',
    category: 'development',
    source: 'openclaw',
    status: 'active',
    keywords: ['development', 'handoff', 'context', 'session'],
  },
  {
    id: 'lesson-learned',
    name: 'Lesson Learned',
    trigger: '"what\'s the lesson"',
    description: 'Analyze recent code changes via git history and extract software engineering lessons.',
    category: 'development',
    source: 'openclaw',
    status: 'active',
    keywords: ['development', 'reflection', 'git', 'learning', 'principles'],
  },

  // ── Planning ──
  {
    id: 'game-changing-features',
    name: 'Game-Changing Features',
    trigger: '"find 10x features"',
    description: 'Find 10x product opportunities and high-leverage improvements. Strategic product thinking.',
    category: 'planning',
    source: 'openclaw',
    status: 'active',
    keywords: ['planning', 'product', 'strategy', 'features', '10x'],
  },
  {
    id: 'gepetto',
    name: 'Gepetto Planner',
    trigger: '"create implementation plan"',
    description: 'Detailed, sectionized implementation plans through research, stakeholder interviews, and multi-LLM review.',
    category: 'planning',
    source: 'openclaw',
    status: 'active',
    keywords: ['planning', 'implementation', 'analysis', 'research'],
  },
  {
    id: 'requirements-clarity',
    name: 'Requirements Clarity',
    trigger: '"clarify requirements"',
    description: 'Clarify ambiguous requirements through focused dialogue before implementation.',
    category: 'planning',
    source: 'openclaw',
    status: 'active',
    keywords: ['planning', 'requirements', 'clarity', 'communication'],
  },
  {
    id: 'ship-learn-next',
    name: 'Ship-Learn-Next',
    trigger: '"ship learn next"',
    description: 'Transform learning content (transcripts, articles, tutorials) into actionable implementation plans.',
    category: 'planning',
    source: 'openclaw',
    status: 'active',
    keywords: ['planning', 'learning', 'implementation', 'action-items'],
  },

  // ── Professional ──
  {
    id: 'difficult-workplace-conversations',
    name: 'Difficult Conversations',
    trigger: '"difficult conversation"',
    description: 'Structured approach to workplace conflicts, performance discussions, and challenging feedback.',
    category: 'professional',
    source: 'openclaw',
    status: 'active',
    keywords: ['professional', 'communication', 'feedback', 'conflict'],
  },
  {
    id: 'feedback-mastery',
    name: 'Feedback Mastery',
    trigger: '"give feedback"',
    description: 'Deliver constructive feedback using Situation-Behavior-Impact (SBI) technique.',
    category: 'professional',
    source: 'openclaw',
    status: 'active',
    keywords: ['professional', 'feedback', 'communication', 'sbi'],
  },
  {
    id: 'daily-meeting-update',
    name: 'Daily Meeting Update',
    trigger: '"daily" / "standup" / "scrum"',
    description: 'Interactive daily standup generator. Pulls activity from GitHub/git/Jira if available.',
    category: 'professional',
    source: 'openclaw',
    status: 'active',
    keywords: ['professional', 'standup', 'daily', 'meeting', 'scrum'],
  },
  {
    id: 'professional-communication',
    name: 'Professional Comms',
    trigger: '"compose email" / "professional email"',
    description: 'Guide technical communication. Email structure, messaging etiquette, meeting agendas.',
    category: 'professional',
    source: 'openclaw',
    status: 'active',
    keywords: ['professional', 'communication', 'email', 'meetings'],
  },

  // ── Testing ──
  {
    id: 'qa-test-planner',
    name: 'QA Test Planner',
    trigger: '"create test plan"',
    description: 'Generate comprehensive test plans, manual test cases, regression test suites, and bug reports.',
    category: 'testing',
    source: 'openclaw',
    status: 'active',
    keywords: ['testing', 'qa', 'test-plans', 'regression'],
  },

  // ── Git ──
  {
    id: 'commit-work',
    name: 'Commit Work',
    trigger: '"commit" / "stage changes"',
    description: 'Create high-quality git commits: review/stage changes, split into logical commits, clear messages.',
    category: 'git',
    source: 'openclaw',
    status: 'active',
    keywords: ['git', 'commits', 'conventional-commits'],
  },

  // ── Utilities ──
  {
    id: 'datadog-cli',
    name: 'Datadog CLI',
    trigger: '"datadog" / "search logs"',
    description: 'Search logs, query metrics, trace requests, and manage Datadog dashboards.',
    category: 'utilities',
    source: 'openclaw',
    status: 'active',
    keywords: ['utilities', 'datadog', 'logging', 'metrics', 'observability'],
  },
  {
    id: 'domain-name-brainstormer',
    name: 'Domain Brainstormer',
    trigger: '"brainstorm domains"',
    description: 'Generate creative domain name ideas and check availability across multiple TLDs.',
    category: 'utilities',
    source: 'openclaw',
    status: 'active',
    keywords: ['utilities', 'domains', 'naming', 'brainstorming'],
  },
  {
    id: 'humanizer',
    name: 'Humanizer',
    trigger: '"humanize text"',
    description: 'Remove signs of AI-generated writing. Make text sound more natural and human-written.',
    category: 'utilities',
    source: 'openclaw',
    status: 'active',
    keywords: ['utilities', 'writing', 'ai-detection', 'editing'],
  },
  {
    id: 'meme-factory',
    name: 'Meme Factory',
    trigger: '"make a meme"',
    description: 'Generate memes using the memegen.link API. Visual aids for social media.',
    category: 'utilities',
    source: 'openclaw',
    status: 'active',
    keywords: ['utilities', 'memes', 'images', 'social-media'],
  },
  {
    id: 'web-to-markdown',
    name: 'Web to Markdown',
    trigger: '"convert url" / "web to markdown"',
    description: 'Convert webpage URLs to clean Markdown via Puppeteer + Readability. Works with JS-rendered pages.',
    category: 'utilities',
    source: 'openclaw',
    status: 'active',
    keywords: ['utilities', 'web', 'markdown', 'conversion'],
  },
  {
    id: 'jira',
    name: 'Jira Integration',
    trigger: '"jira" / "PROJ-123"',
    description: 'Create/view/update Jira issues, check sprint status, manage workflow. Triggers on issue key patterns.',
    category: 'utilities',
    source: 'openclaw',
    status: 'active',
    keywords: ['utilities', 'jira', 'tickets', 'project-management', 'atlassian'],
  },

  // ── Agents ──
  {
    id: 'agent-ascii-ui-mockup-generator',
    name: 'ASCII UI Mockup Generator',
    trigger: '"create UI mockup" / "ascii mockup"',
    description: 'Visualize UI concepts through ASCII mockups before implementation. Multiple variations.',
    category: 'agents',
    source: 'openclaw',
    status: 'active',
    keywords: ['agents', 'ui', 'mockups', 'ascii', 'visualization'],
  },
  {
    id: 'agent-codebase-pattern-finder',
    name: 'Codebase Pattern Finder',
    trigger: '"find patterns" / "show examples"',
    description: 'Find similar implementations, usage examples, or existing patterns in the codebase.',
    category: 'agents',
    source: 'openclaw',
    status: 'active',
    keywords: ['agents', 'codebase', 'patterns', 'search', 'examples'],
  },
  {
    id: 'agent-communication-excellence-coach',
    name: 'Communication Coach',
    trigger: '"review draft" / "coach communication"',
    description: 'Review communication drafts. Email refinement, tone calibration, roleplay practice.',
    category: 'agents',
    source: 'openclaw',
    status: 'active',
    keywords: ['agents', 'communication', 'email', 'coaching'],
  },
  {
    id: 'agent-general-purpose',
    name: 'General Purpose Agent',
    trigger: 'auto-delegated',
    description: 'Default agent for handling complex, multi-step tasks with automatic delegation.',
    category: 'agents',
    source: 'openclaw',
    status: 'active',
    keywords: ['agents', 'general', 'delegation', 'tasks'],
  },
  {
    id: 'agent-mermaid-diagram-specialist',
    name: 'Mermaid Diagram Specialist',
    trigger: '"diagram specialist"',
    description: 'Mermaid diagram specialist for flowcharts, sequence diagrams, ERDs, and architecture.',
    category: 'agents',
    source: 'openclaw',
    status: 'active',
    keywords: ['agents', 'mermaid', 'diagrams', 'visualization'],
  },
  {
    id: 'agent-ui-ux-designer',
    name: 'UI/UX Design Critic',
    trigger: '"review UI" / "UX feedback"',
    description: 'Expert UI/UX design critic and advisor. Research-backed, opinionated feedback on interfaces.',
    category: 'agents',
    source: 'openclaw',
    status: 'active',
    keywords: ['agents', 'ui', 'ux', 'design', 'feedback'],
  },

  // ── Commands ──
  {
    id: 'command-codex-plan',
    name: 'Codex Plan',
    trigger: '/codex-plan',
    description: 'Create a detailed implementation plan using Codex 5.2 with high reasoning.',
    category: 'commands',
    source: 'openclaw',
    status: 'active',
    keywords: ['commands', 'planning', 'codex', 'implementation'],
  },
  {
    id: 'command-compose-email',
    name: 'Compose Email',
    trigger: '/compose-email',
    description: 'Draft a professional email using the What-Why-How framework.',
    category: 'commands',
    source: 'openclaw',
    status: 'active',
    keywords: ['commands', 'email', 'communication', 'professional'],
  },
  {
    id: 'command-explain-changes-mental-model',
    name: 'Explain Changes',
    trigger: '/explain-changes-mental-model',
    description: 'Build a mental model of changes by splitting them into smaller logical chunks.',
    category: 'commands',
    source: 'openclaw',
    status: 'active',
    keywords: ['commands', 'code-review', 'understanding', 'mental-model'],
  },
  {
    id: 'command-explain-pr-changes',
    name: 'Explain PR Changes',
    trigger: '/explain-pr-changes',
    description: 'Generate comprehensive markdown summary of pull request changes with visual impact analysis.',
    category: 'commands',
    source: 'openclaw',
    status: 'active',
    keywords: ['commands', 'git', 'pull-requests', 'documentation'],
  },
  {
    id: 'command-sync-branch',
    name: 'Sync Branch',
    trigger: '/sync-branch',
    description: 'Sync feature branch with the latest main branch.',
    category: 'commands',
    source: 'openclaw',
    status: 'active',
    keywords: ['commands', 'git', 'branches', 'sync'],
  },
  {
    id: 'command-sync-skills-readme',
    name: 'Sync Skills README',
    trigger: '/sync-skills-readme',
    description: 'Sync root README.md with current skills inventory from skills/ directory.',
    category: 'commands',
    source: 'openclaw',
    status: 'active',
    keywords: ['commands', 'readme', 'sync', 'documentation'],
  },
  {
    id: 'command-viral-tweet',
    name: 'Viral Tweet',
    trigger: '/viral-tweet',
    description: 'Transform a raw tweet idea into an optimized viral post for X. 3 versions with posting strategy.',
    category: 'commands',
    source: 'openclaw',
    status: 'active',
    keywords: ['commands', 'social-media', 'twitter', 'x', 'viral'],
  },
  {
    id: 'command-cancel-review',
    name: 'Cancel Review',
    trigger: '/cancel-review',
    description: 'Cancel an active review loop.',
    category: 'commands',
    source: 'claude-plugin',
    status: 'active',
    keywords: ['commands', 'review', 'cancel'],
  },

  // ── System Skills ──
  {
    id: 'keybindings-help',
    name: 'Keybindings Help',
    trigger: '"keybindings" / "shortcuts"',
    description: 'Customize keyboard shortcuts, rebind keys, add chord bindings, modify keybindings.json.',
    category: 'utilities',
    source: 'system',
    status: 'active',
    keywords: ['keybindings', 'shortcuts', 'keyboard', 'configuration'],
  },
];

window.APIS = [
  {
    id: 'bird-cli',
    name: 'Bird CLI',
    description: 'Twitter/X API wrapper for posting, reading timeline, and engagement.',
    authStatus: 'connected',
    monthlyCost: '$0',
    quickLink: 'https://developer.x.com',
    icon: '🐦',
  },
  {
    id: 'supabase',
    name: 'Supabase',
    description: 'Postgres database, auth, storage, and edge functions.',
    authStatus: 'connected',
    monthlyCost: '$0 (free tier)',
    quickLink: 'https://supabase.com/dashboard',
    icon: '🗄️',
  },
  {
    id: 'vercel',
    name: 'Vercel',
    description: 'Frontend deployment, serverless functions, and edge network.',
    authStatus: 'connected',
    monthlyCost: '$0 (hobby)',
    quickLink: 'https://vercel.com/dashboard',
    icon: '▲',
  },
  {
    id: 'x-api',
    name: 'X API',
    description: 'Direct Twitter/X API access for advanced automation.',
    authStatus: 'connected',
    monthlyCost: '$0 (free tier)',
    quickLink: 'https://developer.x.com',
    icon: '𝕏',
  },
  {
    id: 'elevenlabs',
    name: 'ElevenLabs',
    description: 'AI voice synthesis and text-to-speech.',
    authStatus: 'not-connected',
    monthlyCost: '~$5',
    quickLink: 'https://elevenlabs.io',
    icon: '🔊',
  },
  {
    id: 'brave-search',
    name: 'Brave Search',
    description: 'Privacy-focused search API for web research.',
    authStatus: 'connected',
    monthlyCost: '$0 (free tier)',
    quickLink: 'https://search.brave.com',
    icon: '🦁',
  },
  {
    id: 'github',
    name: 'GitHub',
    description: 'Repository hosting, CI/CD, and collaboration.',
    authStatus: 'connected',
    monthlyCost: '$0 (free)',
    quickLink: 'https://github.com',
    icon: '🐙',
  },
];

window.ROADMAP = [
  {
    id: 'multi-user',
    title: 'Multi-User Logins',
    description: 'Share skill configurations across team members with role-based access.',
    hook: 'Log in with your OpenClaw agent.',
    status: 'planned',
  },
  {
    id: 'marketplace',
    title: 'Skill Marketplace',
    description: 'Browse, install, and publish community-created skills from a central registry.',
    hook: null,
    status: 'planned',
  },
  {
    id: 'analytics',
    title: 'Usage Analytics',
    description: 'Track which skills you use most, session frequency, and productivity metrics.',
    hook: null,
    status: 'planned',
  },
];
